---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jitsi-secrets
  namespace: jitsi
spec:
  encryptedData:
    JICOFO_AUTH_PASSWORD: AgC3NVwOmm3Xf9Lh+kIrl+Vp3b182UaIMwLw+9aO8n3iCNsbQ7tJ//8eEw+rrmSfizNf8etwJGt1EqF6xuX3F7P9MB3lVM0I2C+MF9lS3+qHHFraOLiItsZZs4d/IZTA8nIOW5UMs8YMeSdDT1AB7+9zIMXPXu4JXLi+7SbEdoT/v32DIH9JhU/XaxB1JGyMw30edvUBIqnrIVZbyCmXttF1k+MeOZGTjxOM1GuBDocEnW1YQAg1nHkmN38cHPtsn0W9dOchnojGqb70OdnmS8kwFR47zFpwcXAIPfqfpakVVAuuv3X9lACmrJ7amiFYehpLYT6K46mR9nyVoQwosO0rIJuCbDQ+uaH/hBMvQbA+/diaEP3FIfKQx8td4HRtTkrmC4JIKJBxuIqCaEwKvtDq+8Hzn9Kq2/34VLkHB64BjK/or8fGXATj9P9myKtKnaspAaCL+4hAcqrDpqAqkhBR6Sz2ZVPqQ6UmhwTibdmx8lS81zBLCn25aVvPtexnopzGSIDPVZ1em6irieJLP3+UWV/Ael+n7NNak8I4u1N6HydD5YtJeGCno/6AHKCrIkTPULWOOvMEcpjyO7xzsRBoDQgJL/3Xmmz9i0P278oXA9Hdet+Ai20jjpie4EH9DNEQ70KHpjcim7cX229DfRk+1XALLoowP2wHlEOCb/MZrY0WBAeWldtV3ZXX7LlSc3EIA21O52VDTiJpgK7MY/5m9N7H4PkEhP3y4TGKmBUPtA==
    JVB_AUTH_PASSWORD: AgA5o0vtj0cutSj9coUz7Is6QvaqMT3Dm0N+W0MPNihrNrVZ4Qrop0bcg4dEs+A/Qk8kwQE54SVVPMlgA+ve91L9xeekHNDTX5Nx/i/FgT4lfP//JaE934KXUjmiu2r8U+D4eE1oUGKJApg6h8ShC7xPTI1TzfVU5ifjPBBqa7nqa5f5pwIoJiOQyleDXCuYQcXsl4fcO3ABFlUBLBEg3Yw0nt542go5FXWZFcDREWF3hktHEgkRgrw8R+1bgD3Xu0Mp1ft1dyfmVcv3ftz6YYecDsme8nkkZCxweWfH8TMG7Aax+UGLYUAqa+JwRSDv/jTVy2NSd3NBA4WXydNbk6CZDonb5SSHxFRfGWnhOXJU2amdpWEm6xh78oHQkNBd1mtWIqtInhwfewWExN+WuylWmN+Dzo9WRNI0gIohaRBuJfCV7ltBIb/ubONW4NqCOvCHDzW1kLVM6WXIENtNSg3U75GAK8oYvXjbwcYRl4vepSFGAfaHRhhGO547S4sWtBCuv+v7r9F8dZB/lX9U1x5PwOesLZy+NYzkuWDXSgvSleAHgkS5xhxVxaQDVqAfjD37nyDg1l1nfFFdkXy/qi0XEFD3b+GECdS3v3TCFMuDTmvZro3UTqtzedfHgVXZ5SRkmu8kl7tATS/dIwcPsPWRz5WNZluuS8MDqgmZxoSag8ugmUZK/gszs8j6zzvaW0poIh7gZP/kL/EDLu/b2FdwRdwkX7SPaGEufo2Qj0F0Lw==
  template:
    metadata:
      creationTimestamp: null
      name: jitsi-secrets
      namespace: jitsi
    type: Opaque
