apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jitsi-secrets
  namespace: jitsi
spec:
  encryptedData:
    JICOFO_AUTH_PASSWORD: AgB+5fQRaNXM4Jz8XG0R+pMoVTO1tnAgPC1yqI0OZTjp8fAKx+RZ/yNKR+AGZ6x9lOf2MrxiIW3m7+2PuBFLZptr3M/xNu3aZNmVtrEVv2W8CiGrGGZGw6wtIKwDRdGOcdQ1v9RhxQonI8YwoSKgZGqpmPA5KxGrdeL49fh34Wn4spGKcn1Oi7eKZ6YqAjQ+qkWh9wDbOhIXtKG1afBZqXa0Ybt5yNzkYot5EvXXBvzfwN1qyiT3yNBndNDqzvQYhiQDoG7jQxwdtDOozjV4wZJeVXizfv0DJVQsUaDNPXeeRdD9tdOt4GJHsyPDOI8j13ahZvAz8FE0WFnHsHciNUF5VsBafGa8c2G2607ucmQLFjRauBEyXrhOtt2Lc+X8h5Uln9PRYvrZJ8dtvfB/MjtScJ0aayDOpuO8nXGxLi/gpmaESnUxCq9FOHVqp8pAYPm3O5MJrACGqppl4cGGS0X03eRsYhdOw6wRSmgLumB0QO0DqLosT09WIf7dc+6QSZEibNOAEu/jm1jsoie7nJteBAChiDpBtK8yHKGWvv1ndFP5q2H4gLs8yIY+Yzi0BikfqqBy6/4z5ilbIiz6kyZrIF4dptwJlj1I0rClvhBb0L7aeyaZqbf+ivib6brFQkJUFsNaYo1cAOKkz+oczgiE2weihPD2xnQzQjhYUkbXCWOp/Bs+z95N+UAt8aRaja4NQtJseNmxnSBpAPmHbISTAQcGORUrjRlXBRPPUauWig==
    JVB_AUTH_PASSWORD: AgBZI46ndsf7Arb9+iaUbLOwPG9I/q4rQ/pJTpXEv9f4yMIf4Dh4Ms1n/7OobP9UAtOepAxd8e+oGqD1QnXYvF3YV2USa55JbZ2ASfkAhianBWtZ2AWNsfH7Q6VVErRACxtQf9V7k7mhJ6fOqDEhU05mxAYyWfOX3763Q2mORYx1ghvYN9Jw/4t4zcOfF4AGZcfoOIJQcLhu/+sVkJiIyURNWNTwSrfK50cwsab3iXRLRTdJ5Dr1/uloOjqJy2dMBULBuSTl/j1yESb8Uyc6+QwECwf404xRkuJOwIVWNWQlVGXfgceZeJfM0S1MLgiGRsc8dU27P0VnpQxVD51C2eq2LknHjYJt9ZUugZ/QBhPQVAYc0bT7DyLxl8RLEWmGfkWU0OmPcrj8hvtFqiiFpq+ZLUHFruT7BLyX9/ap5+qKw9U1fT/Z3qxDDeBHJasusL8VI70e/Vi0+NnN0wvlo71CeYXrDg+SxD0lvqfCBclc1VpEXmlr71gSNlw99QKfbjVwCpC2rrXuW1kHNltp9NmqcldAdOi3/Zc9Qz+RlkdU73Rcn6Hyamy3xjvJ4F9P4B3+ZndlspckVcBYiAsivOrFly4ICrnMbPfWDKtaeLudkVTw0Hu2fgtY0ouK2a6XxEpnBfvtdYy2NoAqIOPNryGlVlLiyQsKs2fxeCaFyIAHCufeQHdBEYETpUPYYP/7z9tvRiMWD6UozWae+ufkoexnxED1jO0+JHir880WAGGhQ==
  template:
    metadata:
      creationTimestamp: null
      name: jitsi-secrets
      namespace: jitsi
    type: Opaque
