---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: audiobookshelf-dedup-secret
  namespace: audiobookshelf
spec:
  encryptedData:
    api-key: AgAsJvu+3Kc1C/v+RMBKp13i76Cne/AqfGex+UPkfDxdcilmxp9JFQTXldUSKfgMloi24By9qszBNgjtsy3sEKHJ0AJPVYrXEeq1Y+T7lQmAsxgJEDxOO3YeceX5MlqNfQ+DZZvidTF04xS7fc1iROUUWj/bvst1kdhs9U3QOzQsTUdkXiswJClKmaCR/0W8h5TmW3/B5qO/lXZpDEl77N6zJLZhq9EE08im7yLF7nfRNMN2D8CMQkrV43RvQhcnvFIh31O5QFC+D0fkJ2rjN1takXQJH4DnCV0VS1Jl2QIAMyEqkhODcrv3tfe+0OXzieA92o57hjCUGpaILknVWwjSSn+E/V7TSxQDaE77alSyTZAZFSFii/QzaobULzk3Sk7RPKuUg5clSR/46zFyApjfm+fN9P4mNpGlEEcKLWEe9l9Yha4zAsIWdblOI1/oCjPZvl7TMYGb3m1a0Y+w0f6+44Dw63oLeoSVMvs8rkgPduk8iQzaXNnlBqd/e5NU6Lnr8X7MeCFj5IITbEAoBZXUwiUlbKmlrz6sqYUuXtrYQwSnk2zu9wZmdcGeg0Gqwkp6egsd3dKSU7KLhq7iF8xehVcupyLBwYqvRMC2/aGCEElQN+J0FSYtBaDFXpetY+sQ9/2pduXYOC50ifFKwJqZdU5we2N4IV+ANA4eea9/8EWMBqPOhd5zmwmc3VbXtq5xZ0hqWro5XfrdW/aoPEfLsuUEGPK/jrqlEdb6+fZXWAnnKUStv1jsIB9fXzR+Rex2Tkzv1D0Qk+LA2ymQrRnPmXDh0vOhcZy6Z5jLxVGiTpZPOwTbPmONr68qev37AGEYFaHkstn8tcvfBU6nbXof5T99kxG2PiP9KY4NphBbT2sldxtnVSlpsKWAUDIMTlRFuPa0mOi4GKSCqpn6ohOBvEquEzZfxI9LTWev+O94IUShDUfZKA9EsyzuH8a07NfTfY2SCeXJ8LHwYb6kLp/MTTABYw6UQiFp0/hAP/g9h/VsaCE=
  template:
    metadata:
      creationTimestamp: null
      name: audiobookshelf-dedup-secret
      namespace: audiobookshelf
    type: Opaque
