---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: audiobookshelf-dedup-secret
  namespace: audiobookshelf
spec:
  encryptedData:
    api-key: AgBcDa6z5eCC6lmpdqu9dAGTs/qBz4neyznaeCQf8m99ET14M87Jk8SmlUtByszZdtgw9xbTBCQ/e5n5C0rbERXLdjx7V17rpN9iGtS3747OFTou1vd2fzlq34he+LZt7AZEL/zB3X/HBL1dVfEQFT5+xXv52Qm6+ju2UnMT2uKiMZUxyXcZaNtQv4WA2bUiAGFmpLsRmaD+h13qS0HobAo+aJyvVf4btxSObm3iJylYR1UwcPZ06k+fz5wfQksOSVTBHy2B8nhhIhMIyTe0qYBswGBfnxJcaUHe3hdN/ntaJ0/I/bSH+Ug4egfMjE5jG0lt893WFsGe4QOJlQG3hzNg2EzBDl0ulA1HVaCwS6C0ZLxVmb8ZGVjKl9n78PQEwZq2TBTTb4M2a0cFRbRX3/76VYibA2EeQyidnp+h80ywty6AM/+IFjXVceKE2cRUMJU+RKxlBAOV3h1qj+Bn5PxCIwvsJkdGwYkj563dZdPx2Msi1LG2ORXQwvZ6YtbyoVzELXFd74Jew2V16P8KhexOmjm0n+GAS2Bgnh7E5s31mzg+mhtidWUH4zbavSpxK4047JkS2sg6nPg4cpQhpcOV7LBMQbs7Fw6TAS5Hk/mnOWCySgUJhbtb+fbroklo5/dekobyORcOLNEi5fOyFgn+NgdpbXf6jBI/O4/8V5W6EWKk+EMxevRG1z46RFWW6cxSnk7buAlsma17bZ9JJhr7r9DUER3aFlDOIKn2t+l9/iyJJRV++bDmTc5uzv9uy236g5tkmONctDuwc+1iWKE05PmrNguCoA+Q0yNNrMp6mmkjPTgvg5gP77RSI4Ff3WEefbQCan7J0JCrIPLAgMbfPnJsaY9G805jXtWlolNs5maOkvWL04sH4nFcVqa+awGkb+L1W0UumB/sELl4oVKlKG6OxIAvHayUs1jVX/NRxi4jsZiB/pCKsdGEqntjWnb5lIbcdyIE9rmC9jY+JoZnLvlV2BsQgLCRmqUNLk6w0nn+e2w=
  template:
    metadata:
      creationTimestamp: null
      name: audiobookshelf-dedup-secret
      namespace: audiobookshelf
    type: Opaque
