apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      chart: cert-manager
      version: '1.14.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 1m
  values:
    installCRDs: true
    podDnsPolicy: "None"  # Disable DNS policy to use custom DNS config
    podDnsConfig:
      nameservers:
        - 8.8.8.8  # Use Google DNS (IPv4)
        - 1.1.1.1  # Use Cloudflare DNS (IPv4)
