---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-sync-ssh-key
  namespace: cert-sync
spec:
  encryptedData:
    id_ed25519: AgBGwpSFsvqNsayHrnmclcK/GFU66JaRJMNyiu0q1k/u8NnxjymGW2eOrLN8TJOwK1icvO1f/WL1QQ7+cYuZuqYxjdl58Wca9Br5WkmNpIXP8dtUhMdz9JqUGwV+L0FU2A/FHrKQZbFA0iXhCNPNfELJ66fyCBn0NbYm96O+5rCvLem0lms90s2abXPIlZUYEyz9ZSg8rn8DcohYon4TNqfadzbOOQgG7w0Mx/PktUIUxqfbtLMXKVNbwaY8Lr3+3TYw4ejfpTFkwmUvDe/+Z1oQ1+v7ikRD2Gju5dvA/JxmPixKpbyd9UkworQeNBW/ROpowWo8xu0cDRD5vmZy6FE37sFe8h39yNI/X+Zkk60+dcadTd1eijoZV8Wfdel5ObPK9e9Rd/mrj4cc1auUaGpY8qKPoMzCyNTsodVWa/90BnPO4woMbTXIqOdSTqzmRVtbpGDJXB2QoFT4NyCiDdk/+2DJhl1FZXGphjpQ4fHxKaomX9HCYkIYutMVRjKeLcd7HiAXwc89fcWHCpz7qZ1IA3vZ6/juWhXbBlTM06g+GtjCXpbCIkJgdrWwllMys/ZoqnU1o1Ly4VuWFg1dB/ewFIfDJneRghSrry6byuFQD4HuVinM/RW1XvjZkI4KOsBQaJ51ACd9Jc+mc73pLJj34N6zjdvaKX0xc/Y1cmtOW+r6FuKbre6s88Y5sz3gpLCv10lkg6b2UZ+PzDGovEUt6b4iYJbvAicpLfRLS9P2j1F3nrZMCRbZJHHN0BG0FCmZMa20BSGeBMAS4do2W+YDPcukVV4Yk/qSPvtxWDVc0xT+z/SoNZa4nfa74WchUphnVn7LyFENa7hq36qreSmXOVwBbi4mVDujWMgjZQHVc9qiz5ym1r0aZEFuI3RPUlla1yEGweu9NFzNAIxAI+3zok1fX4+5zzIBwEZF+o7sP/YVnT6oNkxb/WA5/WN7xa5Iw6oKG3Sz8X/NZCy11HK/ZiP6IT1iU7Ib4H3KOUNxiUGAvbR3b3XGezR011glaGtSuxsxktLrrFlfc2eGdpYx6XXo1TDrGd3BamuVlduNp+l2BX6kgkPllJdYVjDQ7gzMyWgN7ELrVQ1BN+WeXhsJyUYYJznYToE7SDOBEnd8+YYrFiBu0PFk1l0K1Bz0Rak5UePCe34wvYwvFPw3H+oI/e2VC1tnL89fHrvZwHX+EVVVk4aZ74XBxg8Pr23ajlN7+Y625JkUV1xMdlM5911UC1VIOyLxdKbJWOSM5LlybqF2yA==
  template:
    metadata:
      creationTimestamp: null
      name: cert-sync-ssh-key
      namespace: cert-sync
