---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stirling-pdf-oidc
  namespace: stirling-pdf
spec:
  encryptedData:
    client_secret: AgCtNCgrk/gzDXALKjWcGWoOPrl8cPPAEhcM/1pRuJkaL3nl4+QK/ANcSkoMFp8LcuIyAqREkXs1LOxVuErLTZqBrnXpm/dydZUlBudnNQqBZvv3DkAq+IH2Q450DCqhGvq+YxpHgBrPKmUzXqVq8JNvLC5vi6HyzE1kvOLE+VElBHt3AMzF+k7HGiW6EhRxdU7fFpnV0M1gfHooKi/lKhRDxUqU3zigfn6b0JNyDWCByu+DwtBqyo40m2OzyV8KGmiZQ5EDsWP/Bl+08+zsAWfk5CWN54fuxb7n2pZfau3KjgZbFd3Iq4HMzxuxnH0l0lh+vTgKQ+CDCP5jl356o/O0fKQodsiWb2b0xhoLBWVv8f3SfftDyPNUQlsL9lxrB+F52+FwcAVOKEhAiyoS4cCi9R0X8XSVzImWY+ryzK0ojm/WymYMZt0WRMXLQbuli3cTPWAyDaPUrdX+j1sbKD1oZIwd6KKDLm73i2uW7rqmXDAq8A+W5GNp5EBkrodcpWTk9ncSSMXoqTuZsXVbFQB89D7qM5qcpKIZj9k5STc6MgtAjMoZtDPRg3ErEQVQy41UVqIcKt60w1BWlyU8MV/CXPv6ltauTkwk7ExBdeu76uFFYZ4CeUcaPkWWWxcuUV6HJwoq0BoHK729RFJGIFEVFq4aW66Ju/i3xsHmgys/9hoIAxdzu5Err0BMTn/MLey57nXyx9J428P8upHOqM0McC3hr5C49Hf8558KBftB+0i5jNS0E/7UO9OMzrhM8M4Pku/pyzXLZxO9Roa4f9Cv
  template:
    metadata:
      creationTimestamp: null
      name: stirling-pdf-oidc
      namespace: stirling-pdf
    type: Opaque
