apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: filebrowser-internal-client-settings
  labels:
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: filebrowser-internal
  body:
    maxSize: 500m
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: filebrowser-external-client-settings
  labels:
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: filebrowser-external
  body:
    maxSize: 500m
