apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-json
data:
  settings.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "/srv"
    }
