apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - secret-sealed.yaml
  - secret-oidc-sealed.yaml
  - dashboard-network.yaml
  - dashboard-infra-logs.yaml
  - dashboard-app-logs.yaml
  - httproute.yaml
