---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc
  namespace: grafana
spec:
  encryptedData:
    client_secret: AgCgWYvGbRJ2FS3qKAn8lAAqdXowuQWYodvnlJVadvZUq9Pn4Dmcg2udv0yMpdxAIemX+2LmNfKdhG5OqWbnWBpk58mmmkkwQQRxcqT/hDZMhyNNOWhgZG18QgjjVz96vK5qy6VN+pM1UTuyxshwCggG/3F+3KiJ+0X4IGb7grK7FS19IO+bID7FCbzGy8HHTrinf3Bd7kSHNtwVIDyTU7lGF3opqZWLEDVoQDPrrdgumjuQjJq+dz8SOlU84lpXAdI7xW08gBT567OAZcp7iLk2F+tahVNjsNktuJTrP0V6+KOZ7MrCi2mWnhhjyMHKhZTrEqy7fm1xZyIjHuvEVwHPwrxvva/LURm/cTFl35UxzX8XQHFOLgsmOtDSsFpJWgEqb34RXfGXIoLha7lOZQPactMzWWt2fnT72nenn+e4uJGYVmXWxREnLuR6biP2AIOhC51FTbcf+QlCT8dX0uiNnRvYKDxpjhAesHg2Z+QTLjEIzzwrUi21rRLEVmdt6o7HuYGtpz84e2T8ryCPQ13eOD0rr4jS2jpA6Zc9zaMNwDp4lju/6+ZZiWhseH4EOzfBifv18/nQhmGkk50Z88FKXQo5lfjN0U2ddceZi6Q6ZAdJO9j6wqrm2iuX5RqWrHxtCpz9EyHs9o0DiXrDUUjquvo9U/Ll2dUWRnCrAw43bPW5y/oEMHT4AMCEwJFUTpAWhLBn5dc0Ic1GIW63aDZn4huky86VO6KzZnBohENkKnPiT2jS+oIcRvSI7DmMtA2Los9TCboqXkJfAnmeh0qf
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc
      namespace: grafana
    type: Opaque
