apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
        - name: feeder
          image: ghcr.io/moonblade/feeder:ts_1776394814 # {"$imagepolicy": "feeder:feeder"}
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: feeder-data
              mountPath: /data
            - name: feeder-config
              mountPath: /config
          envFrom:
            - secretRef:
                name: feeder-env-secret
          env:
            - name: UPDATE_FREQUENCY_SECONDS
              value: "900"
            - name: TEST_FILE
              value: "/config/db.json"
          livenessProbe:
            httpGet:
              path: /
              port: 7234
            initialDelaySeconds: 300
            periodSeconds: 300
      volumes:
        - name: feeder-data
          nfs:
            server: nfs.sirius.local
            path: /mnt/primary/root/feeder
        - name: feeder-config
          nfs:
            server: nfs.sirius.local
            path: /mnt/primary/root/config/feeder
      imagePullSecrets:
        - name: feeder-image-pull
