apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
        - name: feeder
          image: ghcr.io/moonblade/feeder:7e85fae
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: feed-volume
              mountPath: /feeds
          envFrom:
            - secretRef:
                name: feeder-env-secret
          env:
            - name: UPDATE_FREQUENCY_SECONDS
              value: "900"
            - name: FEEDURL
              value: "http://filebrowser/api/public/dl/hf_Ov0yq"
            - name: TEST_FILE
              value: "/feeds/DONOTDELETE"
          livenessProbe:
            httpGet:
              path: /
              port: 7234
            initialDelaySeconds: 300
            periodSeconds: 300
      volumes:
        - name: feed-volume
          hostPath:
            path: /mnt/secondary/feeder/
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: feeder-image-pull
