apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
        - name: feeder
          image: ghcr.io/moonblade/feeder:56e90c9
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: feed-volume
              mountPath: /feeds
          envFrom:
            - secretRef:
                name: feeder-env-secret
          env:
            - name: UPDATE_FREQUENCY_SECONDS
              value: "900"
            - name: FEEDURL
              value: "http://filebrowser/api/public/dl/-ZyX3mJU"
      readinessProbe:
        exec:
          command:
          - test
          - -f
          - /feeds/DONOTDELETE
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - test
          - -f
          - /feeds/DONOTDELETE
        initialDelaySeconds: 10
        periodSeconds: 30
      volumes:
        - name: feed-volume
          hostPath:
            path: /mnt/secondary/feeder/
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: feeder-image-pull
