apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feeder
resources:
  - ./deploy.yaml
  - ./feeder-env-sealed-secret.yaml
  - ./image-pull-secret.yaml
  - ./service.yaml
  - ./ingress.yaml

