apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  valuesFrom:
    - kind: Secret
      name: keycloak-secrets
      valuesKey: admin-user
      targetPath: auth.adminUser
    - kind: Secret
      name: keycloak-secrets
      valuesKey: admin-password
      targetPath: auth.adminPassword
    - kind: Secret
      name: keycloak-secrets
      valuesKey: postgres-password
      targetPath: postgresql.auth.postgresPassword
    - kind: Secret
      name: keycloak-secrets
      valuesKey: db-username
      targetPath: postgresql.auth.username
    - kind: Secret
      name: keycloak-secrets
      valuesKey: db-password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: keycloak-secrets
      valuesKey: db-name
      targetPath: postgresql.auth.database
  values:
    ingress:
      enabled: true
      hostname: keycloak.moonblade.work
      annotations:
        cert-manager.io/cluster-issuer: default-clusterissuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      tls: true
      tlsSecret: keycloak-tls

