apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/infra/keycloak/
  - ./dnsendpoint.yaml
  - ./secrets-sealed.yaml
patchesStrategicMerge:
  - helm-release.yaml
