apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx
spec:
  controllerName: gateway.nginx.org/nginx-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
  # HTTP listener (port 80) - for redirects to HTTPS
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  # HTTPS listener (port 443) - for TLS termination  
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    # Temporarily remove TLS until certificates are ready
    # tls:
    #   mode: Terminate
    #   certificateRefs:
    #   - kind: Secret
    #     name: wildcard-sirius-cert
    #     namespace: nginx-gateway
  # External HTTP listener
  - name: http-external
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  # External HTTPS listener
  - name: https-external
    port: 8443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    # Temporarily remove TLS until certificates are ready  
    # tls:
    #   mode: Terminate
    #   certificateRefs:
    #   - kind: Secret
    #     name: wildcard-external-cert
    #     namespace: nginx-gateway