apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 24h
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
  ref:
    tag: "1.4.0"