title: "Apps"
subtitle: "Homer"
logo: "https://static.vecteezy.com/system/resources/previews/002/412/550/large_2x/premium-athena-the-goddess-black-icon-logo-illustration-design-vector.jpg" # Updated logo URL
columns: "3"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
  target: "_blank"
theme: default

services:
  - name: "Admin"
    icon: "fas fa-network-wired"
    items:
      - name: "Weave"
        logo: "https://avatars.githubusercontent.com/u/9976052?s=200&v=4"
        subtitle: "Weave GitOps"
        url: "https://weave.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Sirius"
    icon: "fas fa-star"
    items:
      - name: "Transmission"
        icon: "fas fa-download"
        subtitle: "Transmission Web Interface"
        url: "https://transmission.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Plex"
        logo: "https://static.cdnlogo.com/logos/p/96/plex.svg"
        subtitle: "Plex Media Server"
        url: "https://plex.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Expense Tracker Configuration"
        icon: "fas fa-wallet"
        subtitle: "Manage expenses with ease"
        url: "https://expense-tracker.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Misc"
    icon: "fas fa-box"
    items:
      - name: "Athena"
        icon: "fas fa-server"
        subtitle: "Proxmox UI"
        url: "https://athena.moonblade.work:8006"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Raspberry Pi"
    icon: "fas fa-microchip"
    items:
      - name: "Torrent"
        icon: "fas fa-download"
        subtitle: "Transmission Web Interface"
        url: "http://ubuntu.tailab18b.ts.net:9091/transmission/web/"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

