title: "Apps"
subtitle: "Homer"
logo: "https://static.vecteezy.com/system/resources/previews/002/412/550/large_2x/premium-athena-the-goddess-black-icon-logo-illustration-design-vector.jpg" # Updated logo URL
columns: "3"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
  target: "_blank"
theme: default

services:
  - name: "Admin"
    icon: "fas fa-network-wired"
    items:
      - name: "Weave"
        logo: "https://avatars.githubusercontent.com/u/9976052?s=200&v=4"
        subtitle: "Weave GitOps"
        url: "https://weave.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Kubernetes dashboard"
        logo: "https://avatars.githubusercontent.com/u/13629408?s=200&v=4"
        subtitle: "Dashboard for kubernetes"
        url: "https://dashboard.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Longhorn"
        logo: "https://longhorn.io/img/logos/longhorn-icon-white.png"
        subtitle: "Longhorn UI"
        url: "https://longhorn.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Sirius"
    icon: "fas fa-star"
    items:
      - name: "Expense Tracker Configuration"
        icon: "fas fa-wallet"
        subtitle: "Manage expenses with ease"
        url: "https://expense-tracker.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Transmission"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/120px-Transmission_Icon.svg.png"
        subtitle: "Transmission Web Interface"
        url: "https://transmission.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Plex"
        logo: "https://static.cdnlogo.com/logos/p/96/plex.svg"
        subtitle: "Plex Media Server"
        url: "https://plex.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "File Browser"
        logo: "https://avatars.githubusercontent.com/u/35781395?s=48&v=4"
        subtitle: "File Browser"
        url: "https://browse.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Feeder"
        logo: "https://img.icons8.com/?size=100&id=qpuOQzhOVZ0a&format=png&color=000000"
        subtitle: "Feeder"
        url: "https://feeder.sirius.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Misc"
    icon: "fas fa-box"
    items:
      - name: "Athena"
        logo: "https://avatars.githubusercontent.com/u/2678585?s=200&v=4"
        subtitle: "Proxmox UI"
        url: "https://athena.moonblade.work:8006"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Raspberry Pi"
    icon: "fas fa-microchip"
    items:
      - name: "Torrent"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/120px-Transmission_Icon.svg.png"
        subtitle: "Transmission Web Interface"
        url: "http://ubuntu.tailab18b.ts.net:9091/transmission/web/"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

