title: "App dashboard"
subtitle: "Homer"
logo: "assets/logo.png"
columns: "3"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
  target: "_blank"
theme: default

services:
  - name: "Raspberry Pi"
    icon: "fas fa-raspberry-pi"
    items:
      - name: "Torrent"
        icon: "fas fa-download"
        subtitle: "Transmission Web Interface"
        url: "http://ubuntu.tailab18b.ts.net:9091/transmission/web/"

  - name: "Sirius"
    icon: "fas fa-star"
    items:
      - name: "Homer"
        icon: "fas fa-home"
        subtitle: "Homer Dashboard"
        url: "https://homer.sirius.moonblade.work"

  - name: "Misc"
    icon: "fas fa-box"
    items:
      - name: "Athena"
        icon: "fas fa-server"
        subtitle: "Athena Management"
        url: "https://athena.moonblade.work:8006"
      - name: "Sirius"
        icon: "fas fa-globe"
        subtitle: "Sirius Overview"
        url: "https://sirius.moonblade.work"

