apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  interval: 5m
  chart:
    spec:
      chart: flannel
      version: '0.26.3'
      sourceRef:
        kind: HelmRepository
        name: flannel
        namespace: kube-flannel

