apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: homer
spec:
  chart:
    spec:
      chart: homer
      version: "8.2.3"
      sourceRef:
        kind: HelmRepository
        name: homer
        namespace: homer
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    configmap:
      config:
        enabled: true
        externalConfig: true
        externalConfigMap: "homer-assets"
        externalConfigMapNamespace: "homer"
