apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: homer
spec:
  chart:
    spec:
      chart: homer
      version: "24.12..1"
      sourceRef:
        kind: HelmRepository
        name: homer
        namespace: homer
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
