apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
configMapGenerator:
  - name: homer-assets
    files:
      - config.yml=./assets/config.yaml
resources:
  - helm-repo.yaml
  - helm-release.yaml
