apiVersion: v1
kind: ConfigMap
metadata:
  name: audiobookbay-config
data:
  JACKETT_API_URL: https://jackett.sirius.moonblade.work/api/v2.0/indexers/audiobookbay/results
  TRANSMISSION_URL: https://transmission.sirius.moonblade.work/transmission/rpc
  BEETS_INPUT_PATH: /downloads
  BEETSDIR: /config
  USE_BEET_IMPORT: "true"
  TITLE: AudioBookBay Search
  LABEL: audiobook
