apiVersion: batch/v1
kind: CronJob
metadata:
  name: beets-executor
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
            - name: beets-executor
              image: curlimages/curl:8.14.1
              command:
                - curl
                - -X
                - POST
                - http://audiobookbay-downloader/autoimport
          restartPolicy: OnFailure
