apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: audiobookbay-image-repo
spec:
  image: ghcr.io/moonblade/audiobookbay-downloader
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-app-image
  filterTags:
    pattern: '^[a-fA-F0-9]{7}-(?(ts)[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: desc
