apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik-dns
spec:
  endpoints:
    - dnsName: authentik.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'

