apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: default-clusterissuer
        hosts:
          - login.moonblade.work
        tls:
          - hosts:
              - login.moonblade.work
            secretName: login-moonblade-tls

    postgresql:
      enabled: true
    redis:
      enabled: true

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.secret_key
      targetPath: authentik.secret_key

    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.postgresql.password
      targetPath: authentik.postgresql.password

    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.postgresql.password
      targetPath: postgresql.auth.password

