apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobook-search-authentik
  namespace: authentik
  annotations:
    # cert-manager.io/cluster-issuer: default-clusterissuer
    nginx.ingress.kubernetes.io/auth-url: "https://login.moonblade.work/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.moonblade.work/outpost.goauthentik.io/start?rd=$scheme://$host$request_uri"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - audiobooksearch.moonblade.work
  #     secretName: audiobook-search-authentik-tls
  rules:
    - host: audiobooksearch.moonblade.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-test
                port:
                  number: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik-proxy
spec:
  endpoints:
  - dnsName: audiobooksearch.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-authentik
  namespace: authentik
  annotations:
    # cert-manager.io/cluster-issuer: default-clusterissuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - login.moonblade.work
  #     secretName: login-authentik-tls
  rules:
    - host: login.moonblade.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 443
