apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  namespace: authentik
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |
      http://ak-outpost-audiobooksearch.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |
      https://audiobooksearch.moonblade.work/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    # nginx.ingress.kubernetes.io/auth-response-headers: |
    #   Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
    # nginx.ingress.kubernetes.io/auth-snippet: |
    #   proxy_set_header X-Forwarded-Host $http_host;
spec:
  rules:
    - host: audiobooksearch.moonblade.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-test
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ak-outpost-audiobooksearch
  namespace: authentik
spec:
  rules:
    - host: audiobooksearch.moonblade.work
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-audiobooksearch
                port:
                  number: 9000
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik-proxy
spec:
  endpoints:
  - dnsName: audiobooksearch.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-authentik
  namespace: authentik
  annotations:
    # cert-manager.io/cluster-issuer: default-clusterissuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - login.moonblade.work
  #     secretName: login-authentik-tls
  rules:
    - host: login.moonblade.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 443
