---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    authentik.postgresql.password: AgALNlW9SzYuB2g9438WNckN4vEBE6cSBEKTWFUvEs5FmWCtSS+jg7bEztcjh5B7M/iVC6SpFoA7JEu2fj49rleZc1VNVhmF+XLj7he5bn/N5mKOWUYHoRp7WOXoRR/d7WsOEWWWD5NwO0+164khQio50y4JTBb5aZM3oz7JizPpK1NyylvHFDt0YN5L/Q7YBLx0Algd4sEgshGUC9Al6mH81xzIt2p1Gwb/70I6pJglS7YtlkafOhTvJpCRmZOZBOOOFTWhID5gde2sGBFbFyiBfIwl04T+OrL48s/Y8zlrq31zBDFzu/gwnyoRPGg0mWlszeAQG4qQtF1h4lz9ATdbAN9d5t1OhHiaxDF4H6djbnS47Avnaj3SuUJfSfscbVRHCY24UvmYSPtxQB9LojDpdPOBbDwuo3ORVoGJPTP0odbioObFk9BNgF5UzeAAcebcYfl15Ni/bRgokXrYnGJpah2vrKZPEaLtu4mSssB1UoNqY30UV406RnmcQZubOmLNVfLt3cKSVSWwF6AO97VP3eLz7WchcQ2SZ2AF+Y8f8NYqW4PuDei2SwySPXmSLcp/W1oKc9LXozqO7upvEnK97CVbZGNDQhps25QHyIm9FFnm1JoFq9jG2KE081Wd5RvjzZKa/YDAzkREMelnedJU4yKoVNFIc73qtyeVGIF6mSs4qIwgw2JJnGb+Cf079NR6YUouY9jkb0DbxpniOHnd0RTTITvHTtkFFkX9PLx26/3s5Vw0OEWOugyA9pMSZOzy3AJjRxOMA99ZhD+aGlooDV2oQ95uPY3i7nnasQ4RRA==
    authentik.secret_key: AgA4b9BH8LlXq9M0QuUM+gl9o32xbgIChA+LTirAmax+DpGlk1+/lQc4QVxaMk039sNVe9VDt0JSftQMYwtGx6SuJSl+x0CtN4ULEzNJ7vFSw4ch6xepwTglIP1k9p6exFC2/flwQ+TEX7e4s6DYsm6aK/q4+xOv8u2OrimdCPX85l25qW4iTSSG382WHAzDDkGwM/+gGEU9pxv3A2AERt4089/Jpzd4k5q3Z0c+ACt4ruu99BAoiaDBlwtWP3gGad90DYgGoC38OrIpjFqpLtKK8fiRsd7MTtgi5wvO0TjsC6NxaFqsdDtOizRt/vYfLpY7ZoqV1sCpIiKlAeqpqP2Ow5eYKm1+Cs193kHjgsL0+zXwiEjt+FG2+vnZyceMWLU7ywly4dUusEhhbKMIjRVlt7dE66HrJb7Jk27KZzr9hTM9/QyoWG6GTgKKynyR1MM3oxzzjOf3fcMqwD7LKbU7vW2H/ISbOKrCVdA4dzECscXijWtLXabbGDWkCoynVYGDPwVY896cZGxh1nuUm7+Co3aZ4rlL8HWPtoC95Jkw+qzIzNcCa2MAFqmzDGTjFmTg8fJf3oZbL8p+cvg5IzcKyx9KzOndlNe3N5nsUYwlEjD5GW8UDeqhtW4Dg71HZj/CjHZOL7jgmNr7oVQsRGcpZ9ABR3T2ecbqnZAdlNxPK+zbJxGp1A6j3SK90NdoK8CTex4j0K1uLOTyF0+5QNhNHHOwyQ41gyzCGZz1CcPabe+39UcfKQ6vDXZPnql88NGpw/TqODiBqfCoE1MbcLEh8i+DYaG4RIbn/vUpkFRwBw==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
    type: Opaque
