apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: email-expense-tracker
resources:
  - ./env-sealed.yaml
  - ./image-pull-sealed.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./cronjob.yaml
  - ./imageupdate.yaml
