apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
      - name: settings-editor
        image: alpine:3.22.0
        envFrom:
          - configMapRef:
              name: settings-override
        command:
          - sh
          - -c
          - |
            apk add --no-cache jq

            SETTINGS_FILE="/config/settings.json"
            OVERRIDE_FILE="/settings-override.json"
            TEMP_FILE="/tmp/merged-settings.json"

            # Check if settings file exists
            if [ ! -f "$SETTINGS_FILE" ]; then
              echo "settings.json not found, ignoring..."
            else
              echo "Merging settings-override.json into existing settings.json..."

              # Ensure both files are non-empty and contain valid JSON
              if jq empty "$SETTINGS_FILE" && jq empty "$OVERRIDE_FILE"; then
                # Perform the merge
                if jq -s '.[0] * .[1]' "$SETTINGS_FILE" "$OVERRIDE_FILE" > "$TEMP_FILE"; then
                  # Check if TEMP_FILE is not empty and valid JSON
                  if [ -s "$TEMP_FILE" ] && jq empty "$TEMP_FILE"; then
                    mv "$TEMP_FILE" "$SETTINGS_FILE"
                    echo "Merge successful."
                  else
                    echo "Merged file is invalid or empty. Aborting update."
                    rm -f "$TEMP_FILE"
                  fi
                else
                  echo "jq merge failed. Aborting update."
                  rm -f "$TEMP_FILE"
                fi
              else
                echo "One or both input JSON files are invalid or empty. Aborting merge."
              fi
            fi

            mkdir -p /downloads/complete
            mkdir -p /downloads/incomplete
        volumeMounts:
          - name: config
            mountPath: /config
          - name: settings-override
            mountPath: /settings-override.json
            subPath: settings-override.json
      containers:
      - name: transmission
        image: linuxserver/transmission:4.0.6
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        - name: torrent
          containerPort: 51413
          protocol: TCP
        - name: torrent-udp
          containerPort: 51413
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /downloads
        envFrom:
          - secretRef:
              name: transmission-secret
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        # - name: UMASK
          # value: "022"
        readinessProbe:
          exec:
            command: ["test", "-f", "/config/DONOTDELETE"]
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        hostPath:
          path: /mnt/secondary/config/transmission
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /mnt/secondary/downloads
          type: DirectoryOrCreate
      - name: settings-override
        configMap:
          name: settings-override
