apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
      - name: settings-editor
        image: alpine
        envFrom:
          - configMapRef:
              name: settings-override
        command:
          - sh
          - -c
          - |
            apk add --no-cache jq

            SETTINGS_FILE="/config/settings.json"
            OVERRIDE_FILE="/settings-override.json"
            TEMP_FILE="/tmp/merged-settings.json"

            if [ ! -f "$SETTINGS_FILE" ]; then
              echo "settings.json not found, ignoring..."
            else
              echo "Merging settings-override.json into existing settings.json..."
              jq -s '.[0] * .[1]' "$SETTINGS_FILE" "$OVERRIDE_FILE" > "$TEMP_FILE" && mv "$TEMP_FILE" "$SETTINGS_FILE"
            fi
        volumeMounts:
          - name: config
            mountPath: /config
          - name: settings-override
            mountPath: /settings-override.json
            subPath: settings-override.json
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        - name: torrent
          containerPort: 51413
          protocol: TCP
        - name: torrent-udp
          containerPort: 51413
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /downloads
        - name: watch
          mountPath: /watch
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
      volumes:
      - name: config
        hostPath:
          path: /mnt/secondary/transmission/config
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /mnt/secondary/transmission/data
          type: DirectoryOrCreate
      - name: watch
        hostPath:
          path: /mnt/secondary/transmission/watch
          type: DirectoryOrCreate
      - name: settings-override
        configMap:
          name: settings-override
