apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - name: web
          containerPort: 9091
          protocol: TCP
        - name: torrent
          containerPort: 51413
          protocol: TCP
        - name: torrent-udp
          containerPort: 51413
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /downloads
      volumes:
      - name: config
        hostPath:
          path: /mnt/external/transmission/config
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /mnt/external/transmission/data
          type: DirectoryOrCreate

