apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-sealed.yaml
  - settings-override.yaml

