apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.128
    path: /mnt/external/transmission
