apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
  selector:
    matchLabels:
      type: transmission
