---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secret
  namespace: flux-system
spec:
  encryptedData:
    PASS: AgCu0TwxaY+UTQFNngTxlQudQILyAdTvg9ZuV8GOg+hMjYDN9b0pLX7x69gemEsBupwS8lK0/gebZ3HfCW/Pq0sJSjo3ViCUbvqa8a1ht56vSawtl8G+x2D8xmjgx6FFCYkea3ZFodrCtyywEmI9sOofMb9gpET+QGl5abU/lu2E8n8ifVFXpmtI2aNbfEhnIU44f9AHmyANXJRWStTeCFnSOdEVbV41bvlth8ahdRWJj/vrAzGIxIW5U1A6RtlqrqKw3NMXGL/izgpAg3CoBQ3qUmE5YPKiChAja/vfCnTQpcMGiv/r6EuhaXHfSGlOyqXbFBfALHP2z5r8rIZ837tTPTd4kNMFAd9YM0h/th/DcTv+zu+tAXaHxfVwBAc2WxLMeJ6bqQbZhal/RtkcGfxuw2szAEvj0NNPxP41YeDY4kkOK3KrhV8alNDo4IG9JM+qmaeeI+6vOcAndTi4BrSh/crgR9MHHL2854wvoU119GGcKjiKIuqzXDZnUhBow7qXThRBKSJKDcVWaAXYTjOVUHVX2pEdN8ppNX8fS/pzi4Opce216NLkL3FHVR7Xn4b75iU/9A5Bp7NqXobfOmidZhVS4FwUgMOQjo73G+dAc/J0axjW6Mjf3fA/URTdrAc6SIvbSiA04u1k8SoO1BVg0LIb2ouo8ocqQnyYKfEHnxBUeglXfwDe2KuO2fKa6Nbivsm7ojT7jNnQNXpavGV/HUQSVA==
    USER: AgBr2Xim0M5yVb54ZfmjPJ0Tb//oMpThJCOSo64K2pPKaGZ4Vn67EKXju14tOUdVe3qndWgFX82JYfsHYMDVuXOKLFtSjdVEjeokN2qDQTOSfZkz24dGBDLpaSMMQF1FBPMDyQXKpXZBlVPbZKESGc9Cnj9GaghIb0jj48vpftZ6SM6y5bau5rAo5yy0LhcpWM2wKiCl1pL2IWMDtBc3C3oCWfHP+rwAe4UR1jTT5lr+iCbikiLr15YC8ViCgGc01PQpbTptzIWXS4yuZ8irr6etGDCu9bSa3kWCzBjYG6lqUScJXAuAFQUEK78rwh2F0z4YKM5Op+28eWCkDymXhSL0Fvinb77I44MXmOOtabqphxI7LjCiHTi3TVRPACMtUYSFoMmOFs+ZeAEfWz+v/zBz9flKghK2PwGEJEGHYE2A0z2BF5pvP0kk1YKRe8ayGNmunqWi0UOqtkjAh3DFaN9Y1e0DV0sFvVIOA5iE0wkP/KLoZpq1ovvNzyEp6lGJsrhNCHamSJvyrnG/1d/fYI8lywd5+wH2PHZJJT2j+2ag1jEVpRxB3w03gZhI+HjCrfcTCXMeIOjEiqo8KCkyUSPJTSga1yK9Q9xojGCLj9Z3rf2g/T8X/RWU/OFJjSG129ZI7GAKxNQF3Pp6PX+0FwcbnqN3ovbKVmEbggj1dcgCtRXYndxVd1a0KhrRLzb1FCR0sobx6g==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secret
      namespace: flux-system
    type: Opaque
