---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secret
  namespace: transmission
spec:
  encryptedData:
    PASS: AgBkpSgMTvEKvnneUJ6y67/qs1hjjW6/0fSSKTGJsNNFXcInepWuy4k+Ag5pP1gwtBBKEM2/3pX28pjwbNTYgNZ2UQirNNQHUcCvhb3o68l448KLeuCS2prSlNqGh7ZGwAt1d2glmyM4IupoLkBAdPPyOS/cFrLCNO+EIF7jz7uvlXyxuWi/uda5DEhAru0/hi26YMVD0uJ5vdvBy8EqfPKPMkq2lBMVrItOwaT7mL5UlpS4pSNiEFxL8suDfg/2/IHT0W5Lo/gbAiwXrM/tZjVVvzwbWqF7Br4+gDJutZSn2BJLcZ7F410Ti/3rx9nJ3zEhjiSEEJsTQylmGJT3IVD7856oYY+DKxRXqAquihSFaJBYQbjaq/34WCcxgnNXFaPxZZdNRJBgSBLWZr4uc/7f8aFtEbSIxamJs1B7RYJiPeW8Cv546uqb1l/FXLx65LOwfaSjzEFCa8dwP6OKqZ/lA3OWDH0nT8UeR9oiugGPzhcasIX7AgeIhEXKoKSyltOfoKBrtcU1ue2seKTqBmJ2/BKbwXqOSVsDaXvGun9KzMFIO1EFPqYuiBf0qsctyQ8T8xfl2W5SuXLqHkXf7sp78TSeBghrVPV6QSYsKGhe5x4ge6wh0w6YTS/NiyXF6cVgh8ui35ttU18qYHzyMdMr6RE/c+aV/gBYct2Vc+2GCQNqC/QYJmDG2ygFdhZyFyHw+fQL0VOlt3XoNGmE3IxyD0oijw==
    USER: AgBh6Ujl1hpxoM/GzFX2t0USKAEuw5sgM99uUkHzilmj7hDaiiM9O7miflrizzjm2YYjOgaq32j8co7vZENzaJLTq8BV8kx24gH9XkktvXh+lico9TJtu1uDO567gEMygUMz9wTuKXj44Wd+uXaiVF2xtof3XpLma6UAjgfZX2ddgd4O+xhRgsLBBPfuJRr+tOkMgp8ykTFVKOVG6nn3SojrvP0JCyuDJmgvJxKSqW8d64osapYgBntQI8gu6w8bWaZYqJrz4Xm4BALyDvnku80dlZGIod18KeYWL0Qax2MSRlLu8hXjae9f4U1JvcMUqM5n1d0QMuU/7GwrW2DBFuFR6vOVo2KKL+6Gze2nmXLPSZDN+hb2zsQPKk19cNCYLWsKTSxCzx3NeQYXr7LpuKc4eD1IaTyiFsbR/U8PILjVLDDmZeUDAyq+KJNV7AG8o/yRk34DuJkOBNFNK9tRimtONcsDjkQcbvCCqMLLy0Oo6ewpg7MmIcjg/5jZmz2sTRflemRGlCQlPWWg4Tz0PaF+s7EyVVuJGrYQsShCCOcpZ2AQEwzGBsRj6OruCLIDxmn973eilBu5lTniW5jVMs0kjwLvJW6ULsiRmnb9ewlKhYrbSiqhqIUTYZZFIDhSw+LK16sqH11pqVidUhqwyF+Yx0oSi/uQQC3qh2S+30PdSdCbgnUpa34YYqyZzXpXU040qB3Rmw==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secret
      namespace: transmission
