apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
    - port: 51413
      targetPort: 51413
      protocol: TCP
    - port: 51413
      targetPort: 51413
      protocol: UDP
  selector:
    app: transmission
