apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-override
data:
  settings-override.json: |
    {
      "ratio-limit": 0.5,
      "ratio-limit-enabled": true,
      "idle-seeding-limit": 30,
      "idle-seeding-limit-enabled": true
    }
