apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: sirius
spec:
  endpoints:
  - dnsName: proxmox.athena.moonblade.work
    recordTTL: 60
    recordType: A
    targets:
    - 192.168.1.128
