apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: sirius
spec:
  endpoints:
  - dnsName: athena.moonblade.work
    recordTTL: 60
    recordType: A
    targets:
    - 100.91.212.59
    # - 192.168.1.128
  - dnsName: sirius.moonblade.work
    recordTTL: 60
    recordType: A
    targets:
    - 100.100.145.85
    # - 192.168.1.150
  - dnsName: siriusk8s.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'
  - dnsName: siriusssh.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'
  - dnsName: hades.moonblade.work
    recordTTL: 60
    recordType: A
    targets:
    - 100.75.182.107
