# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-audiobooksearch
  labels:
    blueprints.goauthentik.io/description: "AudiobookSearch proxy application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: audiobooksearch-provider
    state: present
    identifiers:
      name: Provider for AudiobookSearch
    attrs:
      name: Provider for AudiobookSearch
      mode: proxy
      external_host: https://abbsearch.moonblade.work
      internal_host: http://audiobookbay-downloader.audiobookbay-downloader.svc.cluster.local:80
      intercept_header_auth: true
      access_token_validity: hours=24
      refresh_token_validity: days=30
      authentication_flow: !Find [authentik_flows.flow, [slug, google-login]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: audiobooksearch-app
    state: present
    identifiers:
      slug: audiobook-search
    attrs:
      name: AudiobookSearch
      slug: audiobook-search
      provider: !KeyOf audiobooksearch-provider
      policy_engine_mode: any
      meta_launch_url: https://audiobooksearch.moonblade.work

  # Policy binding to allow users with audiobook role
  - model: authentik_policies.policybinding
    id: audiobooksearch-policy-binding
    state: present
    identifiers:
      order: 0
      target: !KeyOf audiobooksearch-app
    attrs:
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "Has role \"audiobook\""]]
      target: !KeyOf audiobooksearch-app
      order: 0
      enabled: true
      timeout: 30

  - model: authentik_outposts.outpost
    id: audiobooksearch-outpost
    state: present
    identifiers:
      name: Audiobook Search
    attrs:
      name: Audiobook Search
      type: proxy
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      providers:
        - !KeyOf audiobooksearch-provider
      config:
        authentik_host: https://login.moonblade.work/
        kubernetes_namespace: authentik
        kubernetes_replicas: 1
        kubernetes_service_type: ClusterIP
        kubernetes_disabled_components:
          - Ingress
        object_naming_template: ak-outpost-%(name)s
        log_level: info
