# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-stirling-pdf
  labels:
    blueprints.goauthentik.io/description: "Stirling PDF OIDC application"
entries:
  - model: authentik_providers_oauth2.oauth2provider
    id: stirling-pdf-provider
    state: present
    identifiers:
      name: Provider for Stirling PDF
    attrs:
      name: Provider for Stirling PDF
      client_id: stirling-pdf-homelab-oidc
      client_secret: !Env STIRLING_PDF_CLIENT_SECRET
      client_type: confidential
      sub_mode: user_email
      redirect_uris:
        - url: https://pdf.moonblade.work/login/oauth2/code/authentik
          matching_mode: strict
        - url: https://pdf.sirius.moonblade.work/login/oauth2/code/authentik
          matching_mode: strict
      access_token_validity: minutes=5
      refresh_token_validity: days=30
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
      authentication_flow: !Find [authentik_flows.flow, [slug, google-login]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'openid'"]]
        - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'email'"]]
        - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'profile'"]]

  - model: authentik_core.application
    id: stirling-pdf-app
    state: present
    identifiers:
      slug: stirling-pdf
    attrs:
      name: Stirling PDF
      slug: stirling-pdf
      provider: !KeyOf stirling-pdf-provider
      policy_engine_mode: any
      meta_launch_url: https://pdf.moonblade.work

  - model: authentik_policies.policybinding
    id: stirling-pdf-policy-binding
    state: present
    identifiers:
      order: 0
      target: !KeyOf stirling-pdf-app
    attrs:
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "Has role \"audiobook\""]]
      target: !KeyOf stirling-pdf-app
      order: 0
      enabled: true
      timeout: 30
