# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-feeder
  labels:
    blueprints.goauthentik.io/description: "Feeder proxy application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: feeder-provider
    state: present
    identifiers:
      name: Provider for Feeder
    attrs:
      name: Provider for Feeder
      mode: proxy
      external_host: https://feeder.moonblade.work
      internal_host: http://feeder.feeder.svc.cluster.local
      intercept_header_auth: true
      access_token_validity: hours=24
      refresh_token_validity: days=30
      authentication_flow: !Find [authentik_flows.flow, [slug, default-source-authentication]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]

  - model: authentik_core.application
    id: feeder-app
    state: present
    identifiers:
      slug: feeder
    attrs:
      name: Feeder
      slug: feeder
      provider: !KeyOf feeder-provider
      policy_engine_mode: any

  - model: authentik_outposts.outpost
    id: feeder-outpost
    state: present
    identifiers:
      name: Feeder
    attrs:
      name: Feeder
      type: proxy
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      providers:
        - !KeyOf feeder-provider
      config:
        authentik_host: https://login.moonblade.work/
        kubernetes_namespace: authentik
        kubernetes_replicas: 1
        kubernetes_service_type: ClusterIP
        kubernetes_ingress_secret_name: authentik-outpost-tls
        object_naming_template: ak-outpost-%(name)s
        log_level: info
