# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-stirling-pdf
  labels:
    blueprints.goauthentik.io/description: "Stirling PDF proxy application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: stirling-pdf-provider
    state: present
    identifiers:
      name: Provider for Stirling PDF
    attrs:
      name: Provider for Stirling PDF
      mode: proxy
      external_host: https://pdf.moonblade.work
      internal_host: http://stirling-pdf.stirling-pdf.svc.cluster.local:80
      intercept_header_auth: true
      access_token_validity: hours=24
      refresh_token_validity: days=30
      authentication_flow: !Find [authentik_flows.flow, [slug, google-login]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: stirling-pdf-app
    state: present
    identifiers:
      slug: stirling-pdf
    attrs:
      name: Stirling PDF
      slug: stirling-pdf
      provider: !KeyOf stirling-pdf-provider
      policy_engine_mode: any
      meta_launch_url: https://pdf.moonblade.work

  - model: authentik_policies.policybinding
    id: stirling-pdf-policy-binding
    state: present
    identifiers:
      order: 0
      target: !KeyOf stirling-pdf-app
    attrs:
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "Has role \"audiobook\""]]
      target: !KeyOf stirling-pdf-app
      order: 0
      enabled: true
      timeout: 30

  - model: authentik_outposts.outpost
    id: stirling-pdf-outpost
    state: present
    identifiers:
      name: stirling-pdf
    attrs:
      name: stirling-pdf
      type: proxy
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      providers:
        - !KeyOf stirling-pdf-provider
      config:
        authentik_host: https://login.moonblade.work/
        kubernetes_namespace: authentik
        kubernetes_replicas: 1
        kubernetes_service_type: ClusterIP
        kubernetes_disabled_components:
          - Ingress
        object_naming_template: ak-outpost-%(name)s
        log_level: info
