# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-html-share
  labels:
    blueprints.goauthentik.io/description: "HTML share proxy application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: html-share-provider
    state: present
    identifiers:
      name: Provider for HTML Share
    attrs:
      name: Provider for HTML Share
      mode: proxy
      external_host: https://page.moonblade.work
      internal_host: http://html-share.html-share.svc.cluster.local
      intercept_header_auth: true
      access_token_validity: hours=24
      refresh_token_validity: days=30
      authentication_flow: !Find [authentik_flows.flow, [slug, google-login]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: html-share-app
    state: present
    identifiers:
      slug: html-share
    attrs:
      name: HTML Share
      slug: html-share
      provider: !KeyOf html-share-provider
      policy_engine_mode: any
      meta_launch_url: https://page.moonblade.work

  - model: authentik_policies.policybinding
    id: html-share-policy-binding
    state: present
    identifiers:
      order: 0
      target: !KeyOf html-share-app
    attrs:
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "Has role \"mdfileshare\""]]
      target: !KeyOf html-share-app
      order: 0
      enabled: true
      timeout: 30

  - model: authentik_outposts.outpost
    id: html-share-outpost
    state: present
    identifiers:
      name: HTML Share
    attrs:
      name: HTML Share
      type: proxy
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      providers:
        - !KeyOf html-share-provider
      config:
        authentik_host: https://login.moonblade.work/
        kubernetes_namespace: authentik
        kubernetes_replicas: 1
        kubernetes_service_type: ClusterIP
        kubernetes_disabled_components:
          - Ingress
        object_naming_template: ak-outpost-%(name)s
        log_level: info
