# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-weave
  labels:
    blueprints.goauthentik.io/description: "Weave GitOps proxy application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: weave-provider
    state: present
    identifiers:
      name: Provider for Weave
    attrs:
      name: Provider for Weave
      mode: proxy
      external_host: https://weave.moonblade.work
      internal_host: http://weave-gitops.flux-system.svc.cluster.local:9001
      intercept_header_auth: true
      access_token_validity: hours=24
      refresh_token_validity: days=30
      authentication_flow: !Find [authentik_flows.flow, [slug, google-login]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

  - model: authentik_core.application
    id: weave-app
    state: present
    identifiers:
      slug: weave
    attrs:
      name: Weave
      slug: weave
      provider: !KeyOf weave-provider
      policy_engine_mode: any
      meta_launch_url: https://weave.moonblade.work

  # Policy binding to allow users with admin role
  - model: authentik_policies.policybinding
    id: weave-policy-binding
    state: present
    identifiers:
      order: 0
      target: !KeyOf weave-app
    attrs:
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "Has role \"admin\""]]
      target: !KeyOf weave-app
      order: 0
      enabled: true
      timeout: 30

  - model: authentik_outposts.outpost
    id: weave-outpost
    state: present
    identifiers:
      name: weave
    attrs:
      name: weave
      type: proxy
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      providers:
        - !KeyOf weave-provider
      config:
        authentik_host: https://login.moonblade.work/
        kubernetes_namespace: authentik
        kubernetes_replicas: 1
        kubernetes_service_type: ClusterIP
        kubernetes_disabled_components:
          - Ingress
        object_naming_template: ak-outpost-%(name)s
        log_level: info
