apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: keycloak
      version: "18.3.1" # or latest tested version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    service:
      type: ClusterIP
    postgresql:
      enabled: true
    replicaCount: 1

