apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-source
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-standard-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gateway-api-source
  path: ./config/crd/standard
  prune: true
  wait: true