apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
  labels:
    name: gateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gateway-api
  namespace: gateway-system
spec:
  interval: 24h
  url: https://gateway-api.github.io/gateway-api
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway-api-crds
  namespace: gateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-api
      version: 'v1.1.0'
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: gateway-system
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace