apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
  labels:
    name: gateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gateway-api-crds
  namespace: gateway-system
spec:
  interval: 12h
  url: oci://registry.k8s.io/gateway-api/installer
  ref:
    tag: v1.1.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: gateway-system
spec:
  interval: 10m
  sourceRef:
    kind: OCIRepository
    name: gateway-api-crds
  path: ./
  prune: true