apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - persistentVolume.yaml
  - persistentVolumeClaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

