apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  values:
    nginxGateway:
      service:
        loadBalancerIP: "192.168.1.201" # Use next available IP from MetalLB pool