apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  values:
    nginxGateway:
      service:
        loadBalancerIP: "192.168.1.201" # Actual MetalLB assigned IP (ingress-nginx holds .200)