apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: seafile
  namespace: seafile
spec:
  interval: 1h
  url: https://haiwen.github.io/seafile-helm-chart/repo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: seafile
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
