apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      readinessProbe:
        exec:
          command:
          - test
          - -f
          - /config/DONOTDELETE
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - test
          - -f
          - /config/DONOTDELETE
        initialDelaySeconds: 10
        periodSeconds: 30
      volumes:
        - name: config
          hostPath:
            path: /mnt/secondary/prowlarr/config
            type: DirectoryOrCreate
