apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  annotations:
    cert-manager.io/cluster-issuer: default-clusterissuer
spec:
  tls:
  - hosts:
    - prowlarr.sirius.moonblade.work
    secretName: prowlarr-cert
  rules:
  - host: prowlarr.sirius.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-outer
  namespace: prowlarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ""
  labels:
    external-dns-exclude: "true"
spec:
  rules:
  - host: prowlarr.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: http
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  endpoints:
  - dnsName: prowlarr.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'

