apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    ipv6:
      enabled: false
    cluster:
      name: sirius
    operator:
      replicas: 1
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv6PodCIDRList:
        - 2a02:8109:8400:60f4:900::/112
        clusterPoolIPv4PodCIDRList:
        - 10.43.0.0/16
        clusterPoolIPv6MaskSize: 112

    enableIPv6Masquerade: true

    k8sServiceHost: 192.168.1.150
    k8sServicePort: 6443

    hubble:
      ui:
        ingress:
          enabled: true
          hosts:
          - hubble.moonblade.work
          tls:
          - secretName: hubble-tls
            hosts:
            - hubble.moonblade.work
