apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    cluster:
      name: sirius
    operator:
      replicas: 1
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.42.0.0/16

    k8sServiceHost: 192.168.1.150
    k8sServicePort: 6443

    hubble:
      ui:
        ingress:
          enabled: true
          hosts:
          - hubble.moonblade.work
          tls:
          - secretName: hubble-tls
            hosts:
            - hubble.moonblade.work
