apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data-pv
spec:
  capacity:
    storage: 650Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.128
    path: /mnt/external/plex/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 650Gi

