apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        ports:
        - name: http
          containerPort: 32400
          protocol: TCP
        - name: tcp-8324
          containerPort: 8324
          protocol: TCP
        - name: tcp-32469
          containerPort: 32469
          protocol: TCP
        - name: udp-1900
          containerPort: 1900
          protocol: UDP
        - name: udp-32410
          containerPort: 32410
          protocol: UDP
        - name: udp-32412
          containerPort: 32412
          protocol: UDP
        - name: udp-32413
          containerPort: 32413
          protocol: UDP
        - name: udp-32414
          containerPort: 32414
          protocol: UDP
        env:
        - name: ALLOWED_NETWORKS
          value: 192.168.0.0/16,10.0.0.0/8
        - name: PLEX_CLAIM
          value: claim-JHewYm15ZFBHgpxAVeCP
        - name: PLEX_UID
          value: "1000"
        - name: PLEX_GID
          value: "1000"
        - name: HOSTNAME
          value: plex
        - name: TZ
          value: "Asia/Kolkata"
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: plex-media
          mountPath: /data
        - name: plex-uncategorized
          mountPath: /uncategorized
        - name: plex-deaddrop
          mountPath: /deaddrop
        - name: oldbooks
          mountPath: /oldbooks
        securityContext:
          privileged: true
      volumes:
      - name: plex-config
        hostPath:
          path: /mnt/secondary/config/plex
          type: DirectoryOrCreate
      - name: plex-media
        hostPath:
          path: /mnt/secondary/audiobooks
          type: DirectoryOrCreate
      - name: plex-uncategorized
        hostPath:
          path: /mnt/secondary/downloads/complete
          type: DirectoryOrCreate
      - name: plex-deaddrop
        hostPath:
          path: /mnt/secondary/downloads/deaddrop/complete
          type: DirectoryOrCreate
      - name: oldbooks
        hostPath:
          path: /mnt/external/old_books
          type: DirectoryOrCreate
