apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        ports:
        - name: http
          containerPort: 32400
          protocol: TCP
        - name: plex-tcp-3005
          containerPort: 3005
          protocol: TCP
        - name: plex-tcp-8324
          containerPort: 8324
          protocol: TCP
        env:
        - name: PLEX_UID
          value: "1001"
        - name: PLEX_GID
          value: "1001"
        - name: TZ
          value: "Asia/Kolkata"
        volumeMounts:
        - name: plex-data
          mountPath: /data
        - name: plex-config
          mountPath: /config
      volumes:
      - name: plex-data
        hostPath:
          path: /mnt/external/transmission/data/complete
          type: DirectoryOrCreate
      - name: plex-config
        hostPath:
          path: /mnt/external/plex/config
          type: DirectoryOrCreate

