apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations:
    cert-manager.io/cluster-issuer: default-clusterissuer
spec:
  tls:
  - hosts:
    - plex.sirius.moonblade.work
    secretName: plex-cert
  rules:
  - host: plex.sirius.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-outer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ""
spec:
  rules:
  - host: plex.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              name: http
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: plex-outer
spec:
  endpoints:
  - dnsName: plex.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'
