apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 650Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
