apiVersion: v1
kind: Service
metadata:
  name: decypharr
spec:
  ports:
    - name: http
      port: 8282
      targetPort: http
      protocol: TCP
  selector:
    app: decypharr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: decypharr
    app.kubernetes.io/name: decypharr
  annotations:
    cert-manager.io/cluster-issuer: default-clusterissuer
  name: decypharr-ingress
spec:
  tls:
  - hosts:
    - decypharr.sirius.moonblade.work
    secretName: decypharr-cert
  rules:
  - host: decypharr.sirius.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decypharr
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: decypharr-outer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ""
  labels:
    external-dns-exclude: "true"
spec:
  rules:
  - host: decypharr.moonblade.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decypharr
            port:
              name: http
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: decypharr-outer
spec:
  endpoints:
  - dnsName: decypharr.moonblade.work
    recordTTL: 60
    recordType: CNAME
    targets:
    - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: 'true'

