apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  chart:
    spec:
      chart: media-servarr/homarr
      version: "0.8.1"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
  values:
    dummy: value
