apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: homarr
  values:
    ingress:
      enabled: false
    env:
      AUTH_OIDC_AUTO_LOGIN: "true"
      AUTH_OIDC_CLIENT_NAME: "Homarr"
      AUTH_OIDC_ISSUER: "https://login.moonblade.work/application/o/homarr/"
      AUTH_PROVIDERS: "credential,oidc"
      AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
