apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: homarr
  values:
    ingress:
      enabled: false
