---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: homarr
spec:
  encryptedData:
    db-encryption-key: AgABFUY1QXchyq+RuANtBniYmFkFVBUUCQ35wwahXfqvdyB66lQdQH3GjYVixScrk0kebNoi+oYUDItGl/NSGra/Va0+wiZ7vqwJzmBv6arCswZngXnEZ0JCAQcyVuRywL0yR2xW+UZywK0UAIea8huMMTab1nAyrP5I17hNVkNFC69x9t04L45Vs0KJoYaG4CDXTHAAedMofcqy4PyHGa283IBkpAhVvECyxw5Wt1hG3977TBfMRPLNyEpr1EbEsMrYIQN+wmw+ILGGTa62ECE0+JopIbFhZngJW67uvfC01f7vWQwh2T+bF8fvth3hPyNQv5UkQA2u2pQSSTQ1DSX0QgEsDUzJ199S5G+y7m+7mqWTQoxoaIBHXhM4lwdHQYhAAAm/v6pCXfBDWL2rlnEMKi0lisqxjYEcOzaVgl4i4hSQEASQDCA8oituTsHlA0r4TWGDQ7SGv6zJtaXsYmnc/5FaA/yVZqr5z9PnmSyGEBfamVW10AN8U4deoQ0rOq4lq49QnnBGFjqDUeWDp3HZ3lj4VydRgjSTK5RBIFfg1DTD4JJjlOJ3xdHLJoR5TQbEIGwxlA5gUHjryHasTdiSeCvGcAViO+i50Lw3y6MLAiqrJw9yELS2t5Yr5q5ewWKgR8na3ZRK8iaB8yl2O1ToTUi4Z7yU6cd0+r3NyH9X5EfS8RJN0gveH1q4HV1bgVDgOWcnpqfU2df62In/wQ5hofSeNC2HAy249uc4J4DRxG/Q3oiTEKRD2dO6LfyY6TEpkWvoyq0OTkQY+gdUHnvO
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: homarr
    type: Opaque
