apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.29.10
    path: /mnt/primary/root/storage/ollama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: ollama-nfs-pv
