apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: mnishamk+sirius@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: moonbladework-issuer-private-key
    solvers:
    - dns01:
        cloudflare:
          email: mnishamk1995@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
          - moonblade.work
    - dns01:
        cloudflare:
          email: mnishamk1995@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
          - sirius.moonblade.work
