---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCf1n4R/HGuUXn/3ll904Nvg/FWsQYAiqY9rY1Z1gu5ka7erJE+cmrPsW8MkT4100ViRmZsvG2L0N7xtX03w/6H0HCx6Sr1pOBHrjFvi57xi2Szn3yddS2UFsHarEMU+GUgPHjuxB37G8w4iaZLrh8mfrsjpX7SOteqAYRGYpCz710vjdEBceMQqEBoasygrs+BcAW4PgMytDAyaY8lQSsSYKf+GnIjl+kZCo9/iALpzr0mEMi7Qw0VcNhVIDdsb0GE9sncgcLMHDQHkGCDUb4czQ7JUdHVlFMam19KrzIgQVJEflE+NK2ebQqKAmUdmUfHLJIVRnHP/KigZU3vhr6Nl7a2bxGZETKOMoF0DtPqZbLodZ2tYxYPieMXplMSb9OGtCjkjtpr2d6C8oXvAyIROw9BAj0VYXB3gIyQ68QI1GQUXYFarP/+rFB0n5TqKAZk6zPP8mMywyevzOlPLeaEq+T8aB8gdPW995tmI6JH3/kI6Fw05e8XtIpspErNyBshU7PsQ6wz5EpKfv8ysaadgTzeMURXSMwIMUZ+gy3cC9o/ObF8v63L7CizMQzeTYeOGskjZw2Q66F7CUWFHms05NB07oWXwwwQz3VUBl0G1wWhdVzD4qwM2oaLnYB2kEsY7AtVDMA2E1AYlBF55lApeFQq1vasuj0iPFi8uA+j+9DN3usJM6Aksvtbxr3Q+Y1S+9/kDLK0jKvtFikGV+tlaDWdtUXn9wC6x72wr9v0yrfpe8DpoUEI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
