---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBJzUR7HIkm7tLhsLZObeF7WEXjLVBX6yxbHY34S081fIea6W3X6KQwe87MWLU5ecV5vdyYoz2hj0XkgrpWNLB7Usfqcz6GdOTfYYRCPOvQ3TzST16IjW0NRXruuMrLMfo9fRHAVm+g1wfdZ1UE13VuqUhrlKqw1G+65ZGIXuicGM2CZ0jp1qMOyzF61KtwmzbqBfBPbEj9UZlc5CmHNBs5hnfiMdv8xQNIYyAZAtCmFrPj5xbg/lxtd3RzMlFB/RM94loVUqXgUxW+ggBWiFa+0SGETQmWuF+Pg5hXSte0YbCum25r72ngVdMW/oudWYETBseb/sQQ8RSMav9tIAzTV3bNB5B2Hi/36co+AA0yx5Md4xxZBIVadwTkJBToWyr4Z16TR7ym465qDHz/Ln05RvdSIIi47ZuV1DdTzDrNsjG5uFSOWwwtn+6PiUYEtnk8EdKxSVzKVU+LtEqJw/VcTqeSf72VKJMWt+UCR0+B1Vad3PP/sf98W+L1SnjuhqDuUd4y2mF2YCEQXtLfno9xAJMHrDSdunArZFi5gTZ1a388IOkqF+JWhBMBlbfrXYEQKZSsBGIbSauwAOtmDmInxCQS0qXDK1Yg+of+r9rIMTY6qYaPUaCPFXRmbC1tZjjDmIuHNEXAhgRoY7oYamo8p8zNSub7MTKAMQrV+tQZRMpKuS6LckMhMKH6ccD3UGkPNQyuVDsq7PKS5IJab5f7AonKKoNu5Nz1h6EnOc5yVqaWPnOHzN+J
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
