apiVersion: apps/v1
kind: Deployment
metadata:
  name: deaddrop-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deaddrop-downloader
  template:
    metadata:
      labels:
        app: deaddrop-downloader
    spec:
      containers:
        - name: deaddrop-downloader
          image: ghcr.io/moonblade/audiobookbay-downloader:ts_1739705510 # {"$imagepolicy": "deaddrop-downloader:deaddrop-downloader"}
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: deaddrop-secret
            - configMapRef:
                name: deaddrop-config
          env:
            - name: DB_PATH
              value: /config
          volumeMounts:
            - name: deaddrop-config
              mountPath: /config
      volumes:
        - name: deaddrop-config
          hostPath:
            path: /mnt/secondary/config/deaddrop-downloader
            type: DirectoryOrCreate
