apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"  # or latest tested version
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    dummy: "dummy-value"
"
