apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: n8n
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    main:
      config:
        n8n:
          hide_usage_page: true
          environment: production
      secret:
        n8n:
          encryption_key: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
      
      resources:
        limits:
          memory: 2048Mi
          cpu: 1000m
        requests:
          memory: 512Mi
          cpu: 200m
      
      persistence:
        enabled: true
        size: 5Gi