apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-external
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/name: n8n
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - n8n.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: n8n
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-internal
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/name: n8n
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - n8n.sirius.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: n8n
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-internal-redirect
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/name: n8n
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - n8n.sirius.moonblade.work
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: n8n-internal-dns
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/name: n8n
spec:
  endpoints:
    - dnsName: n8n.sirius.moonblade.work
      recordTTL: 60
      recordType: A
      targets:
        - 192.168.1.201
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: n8n-outer
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/name: n8n
spec:
  endpoints:
    - dnsName: n8n.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
