apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption
  namespace: n8n
spec:
  encryptedData:
    key: AgA9zBAnn/2XXzjiSjjtboiWwFOJ3RJQ6DgR14jANeidLM4155yyvB58s8gN3Wd+DsGRTNUVFPO7O4tBSLYZvPV4+dKun113ciX5CrCjS6/R3afm6WWjxkRqpuV7nFGc0zLhZYWA5BsnDPBFTMCMguHAdr3JNxy2OneNcJ5ieWTMeY9kHfY9x1FuFtPIa2s3rx2cDRndiyLSj7BlODgauBezimd4+5UcRMrOVqCkIOWeCB15HK+m0V3qCn2syfXxQv2zC7SwjKmJeCXKQ1JS8Rg36Y3E6F6GoiaHn4W6TbYtduuNb4+g0e1eWE2pFFmhTMUeGBSOcvwCVwcVgWK6hSig+LQZpN98UFHKhqfMWBM2TZdgwQJq9HXIduzCYDWKClky8MA6SHRKLhRUKla67WmCYc7/ltAvTDdw9c6OecSaG7/1TzdNt9dBvYocM7Pmx6uyDaecT2VVBeLL5ZrLKa4LRCBi/k9uMmCAOu5pY39A2hjJQIrAIH07f4sRoJmph/b2qwI5Lzg/QVY1omuW78LY9Yx7JXstptaBuBoO9vluEhEDdYGuvQRyq42x9Cg4CrZ8bIjE12c5LNi3ISwq33ArTZKbKKm1dLvcK+bH9bEoN/rTJk3wBZp9YscXPkQZjLUoTk68ThYsGR+C/cvfXgtu0eYb7z2VF8UduvsPq+Fuki/sOKheChI5wCEwN1JgfRDCopcNd3tZ/sADKi7mwYog+4QOrqLo6jgXaXnbYoek4LcyRXymjOzSiwkM3EWasnuiUBdz57tnpgUKuO+wOTYKNEpELvg9S+2yFcgz0+7dqIwO27UrVSpSBXWa36YTDi9gn1CqggV7W7vutinEOWW2c6GnlQJacfM1kXSpuxD5sg==
  template:
    metadata:
      name: n8n-encryption
      namespace: n8n
    type: Opaque
