apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgANSqoHElfZvzHol6e27gJd8FJUvMNTDPRACUlva2F0T0UbPOO4sfQDeGPqhSalCbWCeE2JyTfx2aFr1bY+dHpqTdwH+d0jHnPJiU9tWAkhyALpuiRks5IUyFfkFgETP5boAUoegYtGrvp8RWgcPHsT1S8QLNukZOOwpbxO3yIwrG0YaYBqDCvj0IMznDEvO6uaOHCCOY1PUY85ov3ZDBzqs6WBPHB/P6qGlt45N3UnQQf0A30L+aRK+6YwXG9erUMl5E2srdDQye+6V6w954QknX7mEePndSQx8IxjU5OxxkMabyhBYRz1YGFLzzUiuLPVozk+aHpSLEwp+nY8gwQie2dtxll1z4eMgP35ZNBT5CEKYuNSd+I0kEbO826QCtT5NoNuURD+FLFyp02syEyrb45hsBoeNYJEoAZE0BudV0WUDNFatd5/74PuCeMYq3heNok4bEShzW7BJ9/EXHnWk0rAsEcJu3AFyiuck7g5rJ21GktLHJ5QP1DusizOTRopysqxQe6dE9WlDXKEuTHHOHVlWwbeH8QffyZorN9B0wAQgc68cBZ3vGEBR1mzwYMAxh00axbMwvshVOXif2cC5eQuculRgy0uRDm+BIrQPa3CLU95GC8H81k3Kn4A/vh8Km+fIrgYuLQIkiCHNOocn0SAqsyBZt8bIi41zHHqKuoHrAoFWfC//zh4vyb1yi+5saF8gecSwvBGNImyv0DtZZjYsGal4V/S8szVLI82bhEzrpjMoXeQmMkeSaLqnWRrFhsZcntUBncv22n2L0gS7ZTjV95xldXgZA8IdMBVCvM3bYCqbZH+aUS2h9PnMocDf9NcsupJMCQZWIWyruUe9010kv2E6mbAm4C4x5x7Dw==
  template:
    metadata:
      name: n8n-encryption
      namespace: n8n
    type: Opaque
