---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-oidc
  namespace: n8n
spec:
  encryptedData:
    client_secret: AgAVL/MCDCn2dHi4VOBJgoqdi5aMZ+8ZTTi3FEoDSPOrxb0nt3A1Be7h+r6rn7cS+S6bSI7zEFxGFfJgKDlRKCc62Fj95Q8HOn+ZUwh9iTXf/bkGumqLHrJeePKIeujsdXs5LHunUtkp1s2hA8efRoJzBej4w8c1NHMdbk7q+gZB1JphVPS+J4P44J3H8AHfmvTobHAcjGrAXu70QnP6o7aHr7NFvG9n/z6/x+7fSRICF2BviX+c72K9hG207W6r/k0gcgeyP6DHnuBwR5HSyii5HGcS5rbfdWzcG4A+LwJFiRxJMAlX99D8YVed2Czvw/yluQUodxIgFEwbhp2J0+bxAJE7lOZU7giWRA+NWuUTHxMhsmfKTY5+a9jPC113Jkh8A/54qqWCOdk4YxRO5XUivhLtW8Fw2w91Ps2YBeWIE2YSj/LWWQ8i+BPZaEzk0uGYux8vhAN7I9s0HQxucHQeDBeU7X2HNflPcKgH/zQHvxanrJiIhZW/j6tSpTrBnWLC9a145GkdODcRIdTXLSK4YrjhznVZ6DZp9X3ux7Gmht3tqLs3DCH8scyuda1wIC8E25naMVgzBgf7zfIApunOHPqifGBEHUtgi05XhDdzpvjkfpHuzNYbmnzJdgi48GAcdLbZgBQSrxfmoZw0Vh4OwP+4OUHDEv8kd71Ipv91czHpNWext6POVMQhJSAdgGXhkDgsXBQ/KnwnUcXTC35b6MFZrs/wgFJ17s5WgwtNXvyi+l5NCdOnKVNn1W4fuwW4Ck9NBTjgzWNQLvMGJZI1
  template:
    metadata:
      creationTimestamp: null
      name: n8n-oidc
      namespace: n8n
    type: Opaque
