apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: expensetracker-external
  labels:
    app.kubernetes.io/instance: expensetracker
    app.kubernetes.io/name: expensetracker
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - expense.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: expensetracker
          port: 9000
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: expense-outer
  labels:
    app.kubernetes.io/instance: expensetracker
    app.kubernetes.io/name: expensetracker
spec:
  endpoints:
    - dnsName: expense.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
