---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: expense-tracker-image-pull
  namespace: expensetracker
spec:
  encryptedData:
    .dockerconfigjson: AgAy39uOVRmcJenvOaZ+TIA7yRcLAS9+j5iQ8xsaKWHV1XYA77kJsNR0VoXzV1L9WjVKFADu5GLci3SSzhXwTbKcItTZhoIWwHbZvdPm9Z16G43L3Y3Gd2qIhDPR4xfgxV8v/deygAkVU8Gwi+2qFaP1a5OfXdUkMYF4GLnoM0bSlrl4LEbvc6xkB6Kuo8hc2wjlBhS/eIXTMK65sqPNbnhUnPR/9k6SZrkTcCUcF7z05TC0rtJZqEoAzezsbLind5iPgdts1pogDRgs7mazKekrbrcGiJOhpu7qhXtyggo4kyHo6xcg603StwncclacTRAMRh1ERWNdPr1q9ewymstL+S9OowJBPFtyuNtWrZkeH2v2q/gjqq7z1ojmXMkRBoJTrKiRPiXy8gOhneTcaAADbeuDJYfcafJGp/GZPcx8uP2C6VjlSsB0QO2NpBr8A4p1msQcK5G5/yY35x8fQKYXpJZ8tugcZB5QH3/LiwSmSVESibkCKdy0DiqVlGoHo7bz5BlvToLc+uaZXBEG3wzUSfMxYxGgsaAnPklA3G3LPn0pDC9QpLMu99yE8M6OwHKDxK8eKwhukI/aeXmOUHqAbAVYXkb/ryHa8G9l2oUDeX9Q1dVvZkg2BjBb9FsbwqjK9SzeKpXN++2fC17aeJdJwzv7D2k5TyDqSgijitIUoYhy6QdGejoO+cGFQvbcTR+rPH/nBxayY6PhFfD4GeKk8uMlkbpOSmX3EOk8VH0V8MUbNV0Xxn1ibgt+qpJEBt43Ej0WbHlH1mc6DmtU3XaW3TPrikB0vVsiXJ4IsNRg8V39bQM4SH3VqAiiTDkpsG3JkTAQSOMix/nvzzcKkikhbgk3gscSLSoXD+bt5lJ0Y5tXW8/rpbdgZ2wkzuMjtGpVQ6obdbNJb8TdSwhcQBgkV5d85q4dlp1YqXz7EVBrwC0=
  template:
    metadata:
      creationTimestamp: null
      name: expense-tracker-image-pull
      namespace: expensetracker
    type: kubernetes.io/dockerconfigjson
