apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beszel-external
  labels:
    app.kubernetes.io/instance: beszel
    app.kubernetes.io/name: beszel
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - beszel.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ak-outpost-beszel
          namespace: authentik
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beszel-internal
  labels:
    app.kubernetes.io/instance: beszel
    app.kubernetes.io/name: beszel
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - beszel.sirius.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: beszel
          port: 8090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beszel-internal-redirect
  labels:
    app.kubernetes.io/instance: beszel
    app.kubernetes.io/name: beszel
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - beszel.sirius.moonblade.work
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: beszel-internal-dns
  labels:
    app.kubernetes.io/instance: beszel
    app.kubernetes.io/name: beszel
spec:
  endpoints:
    - dnsName: beszel.sirius.moonblade.work
      recordTTL: 60
      recordType: A
      targets:
        - 192.168.1.201
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: beszel-outer
  labels:
    app.kubernetes.io/instance: beszel
    app.kubernetes.io/name: beszel
spec:
  endpoints:
    - dnsName: beszel.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
