apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii-stack
      version: "0.8.1"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: firefly
values:
  firefly-iii:
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi
