apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly
spec:
  interval: 5m
  releaseName: firefly-iii
  chart:
    spec:
      chart: firefly-iii-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  values:
    storage:
      accessModes: ReadWriteOnce
