title: "Olympus"
logo: "https://cdn-icons-png.flaticon.com/512/10402/10402676.png"
icon: "https://cdn-icons-png.flaticon.com/512/10402/10402676.png"
columns: "3"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
  target: "_blank"
theme: default

services:
  - name: "Sirius"
    icon: "fas fa-star"
    items:
      - name: "Expense Tracker"
        icon: "fas fa-wallet"
        subtitle: "Manage expenses with ease"
        url: "https://expense.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Transmission"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/120px-Transmission_Icon.svg.png"
        subtitle: "Transmission Web Interface"
        url: "https://transmission.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Feeder"
        logo: "https://img.icons8.com/?size=100&id=qpuOQzhOVZ0a&format=png&color=000000"
        subtitle: "Feeder"
        url: "https://feeder.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "n8n"
        logo: "https://avatars.githubusercontent.com/u/45487711?s=200&v=4"
        subtitle: "Workflow Automation"
        url: "https://n8n.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Admin"
    icon: "fas fa-shield-alt"
    items:
      - name: "File Browser"
        logo: "https://raw.githubusercontent.com/filebrowser/logo/master/icon_raw.svg"
        subtitle: "File Browser"
        url: "https://browse.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Weave GitOps"
        logo: "https://avatars.githubusercontent.com/u/9976052?s=200&v=4"
        subtitle: "GitOps Dashboard"
        url: "https://weave.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Search"
    icon: "fas fa-search"
    items:
      - name: "Audiobookbay"
        logo: "https://audiobookbay.lu/images/audiobook.png"
        subtitle: "Search audiobookbay"
        url: "https://abbsearch.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "YTS"
        logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Logo-YTS.svg"
        subtitle: "YTS search for movies"
        url: "https://ytssearch.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Media"
    icon: "fas fa-headphones"
    items:
      - name: "Audiobookshelf"
        logo: "https://www.audiobookshelf.org/Logo.png"
        subtitle: "Audiobookshelf"
        url: "https://audiobook.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Jackett"
        logo: "https://avatars.githubusercontent.com/u/15383019?s=48&v=4"
        subtitle: "Manage indexers"
        url: "https://jackett.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Stremio"
        logo: "https://www.stremio.com/website/stremio-logo-small.png"
        subtitle: "Streaming Server"
        url: "https://stremio.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Misc"
    icon: "fas fa-box"
    items:
      - name: "Blog"
        logo: "https://cdn.pixabay.com/photo/2022/01/16/16/44/blogger-logo-6942640_1280.png"
        subtitle: "Blog on github"
        url: "https://moonblade.github.io/blog"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Athena"
        logo: "https://avatars.githubusercontent.com/u/2678585?s=200&v=4"
        subtitle: "Proxmox UI"
        url: "https://athena.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
