apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kokoro-external
  labels:
    app.kubernetes.io/instance: kokoro
    app.kubernetes.io/name: kokoro
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - kokoro.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ak-outpost-kokoro
          namespace: authentik
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kokoro-internal
  labels:
    app.kubernetes.io/instance: kokoro
    app.kubernetes.io/name: kokoro
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - kokoro.sirius.moonblade.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kokoro
          port: 3002
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kokoro-internal-redirect
  labels:
    app.kubernetes.io/instance: kokoro
    app.kubernetes.io/name: kokoro
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - kokoro.sirius.moonblade.work
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kokoro-internal-dns
  labels:
    app.kubernetes.io/instance: kokoro
    app.kubernetes.io/name: kokoro
spec:
  endpoints:
    - dnsName: kokoro.sirius.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - gateway.sirius.moonblade.work
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kokoro-outer
  labels:
    app.kubernetes.io/instance: kokoro
    app.kubernetes.io/name: kokoro
spec:
  endpoints:
    - dnsName: kokoro.moonblade.work
      recordTTL: 60
      recordType: CNAME
      targets:
        - 46b0a967-3b0f-493a-88e7-6f1cc9f8852b.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
