apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poker
  template:
    metadata:
      labels:
        app: poker
    spec:
      containers:
        - name: poker
          image: rom14700/pokerth-server 
          ports:
            - containerPort: 7234
          env:
            - name: POKERTH_PASSWORD
              value: "pokerth"
          volumeMounts:
            - name: poker-data
              mountPath: /root/.pokerth
      volumes:
        - name: poker-data
          hostPath:
            path: /mnt/secondary/config/poker
            type: DirectoryOrCreate
