apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download
resources:
  - ./deployment.yaml
  - ./configmap.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./secret-sealed.yaml
