apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      ingressClassResource:
        name: nginx
        default: true
      service:
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
        - IPv4
        # - IPv6
