apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096 # Expose this port
      targetPort: 8096
      name: http
  type: ClusterIP
