apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: media-servarr
        namespace: sonarr
  values:
    ingress:
      enabled: false
