apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - oci-repo.yaml
  - nfs-volumes.yaml
  - postgres.yaml
  - helm-release.yaml
  - httproute.yaml
  - secret-sealed.yaml
