# HelmRepository with type: oci for Immich helm chart
# Flux helm-controller v1.1.0 requires HelmRepository (not OCIRepository) as sourceRef
# https://github.com/immich-app/immich-charts/blob/main/README.md
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: immich
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/immich-app/immich-charts
