---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    db-password: AgBYGjSzZbGaWk0i49/CQZQ9BE4099jjHgEkK5OG9pzSJ///5fRyzb+6WL2TntTE/RT+vChoBJkeXljaJXKYfL60bTMl1VR+qIg28+XnQd6po5+VjdruLe7FuqeDcnN6GJs4ynfkwPmN4pJVLTIN9Lxw9Xj7rDMhOiKJDg22Z10/8Lcrd492+RoHSkJJinZS7Ai5GPDjTb3LFHlzzQdEkWGXEteTR+6RBqsz8QwIm9tma4pgBwJ9QnhH1JZbK3vlPM0vwpH5Kg4bv5zZe9ojDP3XMOy0Q5P9skGBtolwg/jdujbw+RHY0NQ31g5i34NGUxlq/LvXMq0Mr6Tam14N8Ob4hQW9znMDNEGEP/wv1DCmETCKPbvcFBlgkFLLqCCYwpwxBrNwIOMn5s71OkSHHPRFzJpO5yZjrim4X/yVW9LNyLTJudupActYjdX7A3V2uT0O9TynuT9Hcxc3BAvXRovThVsjemhncFvO6khuwznDRZdwXy+5AiqWyCqK80OIzCdhwgnbGVslqS+T4shTDbTGKdx8u2fH0BtP7+nzti9uMqC0sdQsPDmUhJ2DqSI5ikAKKDVl0+mv1CK7lfM1GJF5Xh0me52BhUNOb6gRhNNhpbVFQSpRzKMSMOF+ml8FKKPI9SwCrNsGqGGhK3q4ldTmSpvddsLMLZjJG+luENCntfcA7ULhPP4ss/gGvC6fBXmvqbETYyKsk7513nA7Rh9WrZ0IKU9PIYtx9SX4
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich.json: AgC4d6Sf2sTc0d/P2DxRz5qyOX7d1ovElqBvhv9/hyLAXpNgjx0ZuP8vGGEZjR2yQZdVzELkpLE3wP8jQdHhApmsxMdpkXkpfDbUtS6Km5g7TfuxsWshNUy0hyvdpKlXvYu5nj4oBXxlHn+Zy+vHxMA39ByYdFFFxfnVDmpqTscrJb0su3cSgW5s7HHBd9K6OHwt1Bj7KFV7EIbYHDdROGIpYZXV+CBu45mpYfdd54zBuOfzEO5eJpLuJ5IxM/AKsdIdvzR47R35Ia6WvDRhTWW/H8NCEbpg/ngLeDj0b7b/A1857wI84iTyXMJbl2zQWfP+MyXcruO9YDiHGtpzc84wRYl2HzKjVRnetEqMGngWPfbyn7xDeU8Fhz+YMSytMgZ3k7Y+8TEcr4q3ePA3siyuHSoL/LJ472iDGEskDtTQlXk0nLsUOIazF+ZGc7TE2rFB+4hTdiRMNHZ/9mHW/mVctg2g4MdoMdSeyu6K6u/w2TcaVx9S84mDlcjB66IXmaaZ0OgwZfk3WDZX4Thyv3/T5qodAOmDN1t/80ftjT8GwFdSiYI9JUKSi34dowliTuafFDDRhAWSxNDdEUKAZTWRerK9akFXDFR4mtVJqPW7Tn1lSiHH7kZ7zUNXoYgpHiIIdClXnrZdhh42PgPZNJPoXdKRqgyYzwxVkxeerLlYdsv+iptTkc8Xqc1Op/ZCP17rIg24qeSbr5RB6nPzEWPtcGt83YbRo8SU/sDBOrH3BRF1c6DO4LB+fOGxGONNdkFJPl7E2sbgHI3qwLkEVUrVyIJ0Phlupg16t5b7gPu39wRbZxqCtf26G7TMWufteSReKbXxy88FNAQopvfgBnp6d0FfmahasD6zP4zlAZ4YHRXBL/VsZJa7AidTOxcf76t5mHtIHVtx2D1SX4ZPWFYlyj4i9q+Z+aGhNLIr0OyAYP4BIYyWIH9ZQdO864U9MGCsX2+KRYslr93TrouQWmhzrmpXYqW/trsQWxwHm8PB1LqdWhG+x9NRlz0gbfVH3VBL38viBe4VdTkHzwzOBHa4nx/slFAu1s35JCrMLs4w/x0c7Z6u0CRGLwb6uaCfYCoLMwLLwhClR7/K/HWJ833bwXLP0G/NXplaQKsM+te+ereE69PPFsfATz0+CKWuqbBoQNK/pxKvZfLvYX0BzMKnazvRyfXELLi4Q+PmJA33VsxmtXMeE3nlBGG3Gpqr3Go1nAszf6oCWr5ANCKHQD2UwLNqGyHibql67+NWiPPQxpIm9qJCjuQMfZVg5QFecsVlDP+8zk8XpEIpIZg8khgkbgPHS3mYEghf7UcNs5ZhSfJj1kuVDa37IDTQRtD1I+GoiO9ksLDCpp3ox38nGhhokhTeUXPmubFHURqcYG8Dw7h78hs=
  template:
    metadata:
      creationTimestamp: null
      name: immich-config
      namespace: immich
    type: Opaque
