---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    db-password: AgADpZKttnGnzFchdSGxOHhr6ReCTT+Gx6gF7yWghgw0l/WSGEmoLV/hT8UbDkskxQ/5+rzSgEk5OuM8gFfkYkoAg7HfUDbOV/m3jeTINW42MUVjHtI70vqa7pwTrPwseC1bphAkO+DSNKfbiQOD363c3qlRMvSb058gnHJ6nHbE5zfQYR4s/7nI3fivr4YMkT2P9DBH2b2ARRKfqhtroDUKikl19H9LkhDA1Z+/xtPYSSt511N78xOCRry9XDj4ci5VFJ22AdJea8il+ZQSla7mIU/CY+4itWJk+zbCs+P2Z9ZQBtdm/AN33hqTCN2EKJy5D/aSoxhWKOqHcguUGRcIHiFFADtyLj3VuV2mMhL6sCsEsJeZ7ENvl6Uwq579M/mal7kAol9Qpg5CODFssa7PfinY9pgPFscKkgivy9YZNbBQYiGOogCRtdJS8x1psf6avGTg06Eq0Qz1VML+husGnZqmf8h1/nIxyVVL2S0o5ad7bve4eVhw4tOTYg68IbW5ZYsjjho5H5AdfHUqwrXc2ggH6OO9H11cZ0YAJfdsvmmaD3PFOltRxbjjvBdmhGNzfJdLpTZXDb5a2QEyvs0ANEl6QGzjhjZq7Tj2biyYhIEW7HV2bvgfGBMUJewVdBUJ4IS7FFZHlmX88JhOayVGM0sVQWPs9ruAOJgTpo3r2AsPhZzd9jq/BOVdSsmf+xSDG7IQw1CIjbzjEimCnzhCD+LSvKlQS9inW6GT
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
    type: Opaque
