---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    db-password: AgAnk2T2oGQTp9BgCgEHEFDmPbMY9VGqRwOApudfUbGHsjS3VUsKFu8yRMI+L/OOvkRX9OqFt/sA3cEDnLuKpe92bm/ch1ivMIJfPd4+XUGcjMfLR7B5KUvBHvxDv2Q/7DSFsHVSXmjBjWjYA92T52Nphw1+Ht48J/8ModBYmK1GNIU/nZieUeKkISa1bfgcp1olY6dsO2AWisVg9hgIsTFrWJFM6YqsVglZC5QSTxCalhutAj5h18akSI6TEdelBrlVHge6NlC6t2GUQBwuC7o2z7nMlDJNoOG+NINMlftVGuomed0eOIewnhFuNWhjapM4PzPmL0ieclvoYwJcuRqdj5g9Dl9p2icNn9k3FT8Ew2O1ywiB4c2Uy6yRGtin2VY5YHsvVhwKbH1Q6du/6SQ6nFwMUaZ7IuX32QYuMWEUvBirlSRk4zs4ZXfGt9ltBbVQnDzzrFbzOvVE2HM+TWjVCf2sjdwrBEEXUxgca7Y2Cb21wT57eOln6qKzzBxQO7vePbPvom/XK8sVlx0sC7hUo+s28r6tR8Mo+JjfmNi19kQLU4ewO58eSNv/HPAyrVr+1RmhH/gAOUzPw/5D9ZklyS/zZ41g2a495YVlUAi4l+phs3CACs2+k1Y3NUo5uhLoWOOmjPpSTh2oh7LHpWsuEL1uJOjXoNzxZYXI2JfOXca1N8W8kUtdrlDt+vmxUztP8pKstEbd0koh+r7txxypHR4a+Szjz+wGgm+c
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgC3EKpRM0+rCv3HmnJhhf0NmlNxPoD7bt/N2rqR2Uh/2efzoFLxn6FJsvW2qJMPwUn1kDBxJ71FirJlPJ+rsGee+60cJ2Fv7RgSdc0Pp7g5iPX8KSnRVPghFmc8h65726ZMmsLbjuyAfqS3OAPfanGqjVIqeDuqA0tVgGLXCfM2+OZillKrYCxMtuGZExKXYQB/FZDlop/CPsdMKNmZeTJ7cOklm3bbFn+261n5J+sQ2Tvv4xuspZFjQoqMUIOdQK7VnCMrULBmhDVW1o2gGhoL5Tx6WRypayx/eitgsCIfA5upsECKhA/cM1TeDwVETM8CEztGNaHC19GDKie46QhfvZ3oYdHHePEpdb0niLL6MBH28PnlunjKhPLMk5gz18TuLosQmVeSUecTq4ZDdL3ixyvJ+NY8qd3bF+0XtgWfzzMPmcSxoA+d9SPUE+Jdm9Lb6fk2Wtmf6ZyKoXLsWp4gVRPJ1z23SJ9Qqxx8cK23x2jRSsg0I3cGcwwU4Fem7IhYJIauPO2a8eZDrHnPoaBzQ6stYCBnmfkWVpiE0xz/F93SbR9Mx+/6lYA10ApmEmOrp6AhDkxoh3sZKYuoTlNVZxS0TFc3X3YzxYC+c9uyLLXf8UP4RRP0t2JwDsaOt/VK61bLL2GkOyQ3VDYuXoIGw5oyHTQSAN3NbTp/Js5R2CoGKfEq3ErdVjmsSKEQRpTo8CHHDRNNiYec5vcZemxRcYbE9dCpyz4WdNtDcfjiRiUPllmohc1abKuhJIUvMN73tkHiF9E7PT1LGgwrjUkXc94jzkivAMefg6CooYMrCfHR8EuzRwGP7wGvUYiVsIBnmCbaKqNNclMH+f7wpSjkvdemGzS/ieUa07A124aH/8rl3aC8LQbpg/kBX+KR8RuTNSHkD/t7dLBOi9uaXkViixDu1qacDm4xboz7TRhw7nhWhHqRn9PdoJyXnzv0y17B5g6B1cfpn0dXbcHRPLRnhrYOOAaLap7is82qUoD1nPI4oej+n2O0MnhZKyP9ZAjhTcLrV+jWwcH4eLnOQtEl09/RoPkRJ8xIIO5e534utC1u09hZFmmHipr6kR8+CH3g4laJdAfFZoMySHTB/qGqHD3Fjklntg6ahV0Q/d3a47vI8nb7aJOOSM8h1Y/2DvCA2PehJXB/aU5Gv9Cvc5r4T1rN44Wlb5LcNGZqlpxO5QzBGRJ1CHpm/SKRs507Bx0iSggJkqmx75saVYJKNz6tyrRrWnUcPBtJ/mZsmHued+BFiwiWBp5BFfO5yYeI9NtxDepL3bixAVOYO+e5/Qb4iV2uUewDQJ/s8zLLj24/Un8SgcOGIauBvIU89lvVleiGMCJ5YEH3t7n2LQlDqkPC+nk0cWfxckibBLf2jLwNBqVVIBY=
  template:
    metadata:
      creationTimestamp: null
      name: immich-config
      namespace: immich
    type: Opaque
