apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: beets
  template:
    metadata:
      labels:
        app: beets
    spec:
      containers:
        - name: beets
          # image: lscr.io/linuxserver/beets:latest
          image: ghcr.io/pspitzner/beets-flask:sha-96360da
          command: ["/bin/sh", "/entrypoint-new.sh"]
          ports:
            # - containerPort: 80
            - containerPort: 5001
          volumeMounts:
            - name: config
              mountPath: /config
            - name: audiobooks
              mountPath: /audiobooks
            - name: downloads
              mountPath: /downloads
            - name: oldbooks
              mountPath: /oldbooks
            - name: custom-init
              mountPath: /custom-cont-init.d/install-deps.sh
              subPath: install-deps.sh
            - name: config-yaml
              mountPath: /config/beets/config.yaml
              subPath: config.yaml
            - name: config-yaml
              mountPath: /config/beets-flask/config.yaml
              subPath: gui-config.yaml
            - name: entrypoint-script
              mountPath: /entrypoint-new.sh
              subPath: entrypoint-new.sh
          readinessProbe:
            exec:
              command: ["test", "-f", "/config/DONOTDELETE"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          hostPath:
            path: /mnt/secondary/config/beets
            type: DirectoryOrCreate
        - name: audiobooks
          hostPath:
            path: /mnt/secondary/audiobooks
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /mnt/secondary/downloads/complete
            type: DirectoryOrCreate
        - name: oldbooks
          hostPath:
            path: /mnt/elements/old_books
            type: DirectoryOrCreate
        - name: custom-init
          configMap:
            name: install-deps-config
            defaultMode: 0755
        - name: config-yaml
          configMap:
            name: config-yaml
        - name: entrypoint-script
          configMap:
            name: entrypoint-script
