apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beets
  template:
    metadata:
      labels:
        app: beets
    spec:
      containers:
        - name: beets
          image: lscr.io/linuxserver/beets:latest
          ports:
            - containerPort: 8337
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - name: config
              mountPath: /config
            - name: audiobooks
              mountPath: /audiobooks
            - name: downloads
              mountPath: /downloads
            - name: custom-init
              mountPath: /custom-cont-init.d/install-deps.sh
              subPath: install-deps.sh
            - name: configYaml
              mountPath: /config/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          hostPath:
            path: /mnt/secondary/beets/config
            type: DirectoryOrCreate
        - name: audiobooks
          hostPath:
            path: /mnt/secondary/readarr/books
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /mnt/secondary/transmission/data
            type: DirectoryOrCreate
        - name: custom-init
          configMap:
            name: install-deps-config
            defaultMode: 0755
        - name: configYaml
          configMap:
            name: configYaml
