apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: beets
  template:
    metadata:
      labels:
        app: beets
    spec:
      containers:
        - name: beets
          # image: lscr.io/linuxserver/beets:latest
          image: pspitzner/beets-flask:stable
          command: ["/bin/sh", "/entrypoint-new.sh"]
          ports:
            - containerPort: 80
            - containerPort: 5001
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - name: config
              mountPath: /config
            - name: audiobooks
              mountPath: /audiobooks
            - name: downloads
              mountPath: /downloads
            - name: custom-init
              mountPath: /custom-cont-init.d/install-deps.sh
              subPath: install-deps.sh
            - name: config-yaml
              mountPath: /config/beets/config.yaml
              subPath: config.yaml
            - name: entrypoint-script
              mountPath: /entrypoint-new.sh
              subPath: entrypoint-new.sh
      volumes:
        - name: config
          hostPath:
            path: /mnt/secondary/beets/config
            type: DirectoryOrCreate
        - name: audiobooks
          hostPath:
            path: /mnt/secondary/audiobooks
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /mnt/secondary/transmission/data/complete
            type: DirectoryOrCreate
        - name: custom-init
          configMap:
            name: install-deps-config
            defaultMode: 0755
        - name: config-yaml
          configMap:
            name: config-yaml
        - name: entrypoint-script
          configMap:
            name: entrypoint-script
