apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-script
data:
  entrypoint.sh: |
    #!/bin/sh
    pip install --no-cache-dir beets-audible beets-copyartifacts3 flask flask-cors

    /repo/entrypoint_fix_permissions.sh && /repo/entrypoint_user_scripts.sh && su beetle -c /repo/entrypoint.sh
